### ISSUE TITLE
Harmony verliert Szenen

### ISSUE THREAD

**Issue by TheRoolBool** [thkl/Homematic-Virtual-Interface#1]
Hallo, das Plugin vermischt die Szenen der Harmony Fernbedienung sobald man eine neue Szene an der Harmony erstellt. Dadurch funktionieren dann die Programme auf der CCU nicht mehr :-(

**Comment by thkl** [comment]
Ja, das habe ich auch festgestellt.
Ich schau mal, ob ich das irgendwie verbessern kann.

**Comment by LevelOne2k** [comment]
Ist bei mir auch so, und schon etwas nervig. Aber schon das daran gearbeitet wird

**Comment by thkl** [comment]
Naja das Problem ist , das die Harmony einen Index (1-n) der Szenen erzeugt. Diesen Index nehme ich für die Zuordnung zur FB .. Dummerweise wird der Index komplett umgeworfen, wenn eine neue Szene eingefügt wird. Dadurch ändert sich natürlich die Zuordnung.
Es gibt noch eine ID für jede Szene, ich muss erstmal sehen ob die wenigstens gleich bleibt

**Comment by TheRoolBool** [comment]
Dann hoffen wir das doch mal

**Comment by thkl** [comment]
sodele ... sollte jetzt gehen. Ich speichere die ID der Aktivität im Master Parametersatz er Fernbedienung. Und beim Neustart des Layers wird geschaut, ob es die ID schon mal gibt.

**Comment by TheRoolBool** [comment]
Alles klar. Werde es später am testen. THX
