### ISSUE TITLE
HVL - Plugins werden nicht installiert

### ISSUE THREAD

**Issue by K3vb3rt** [thkl/Homematic-Virtual-Interface#101]
Hallo, 
ich habe das Plugin auf meiner CCU3 (RaspberryMatic) installiert, aber es lassen sich keine Plugins installieren. Anbei das Logfile. Kann man da was machen?

Sat Feb 01 2020 15:25:03 GMT+0100 (CET)[Homematic Virtual Interface.Server] [ERROR] - Error: Command failed: cd /usr/local/addons/hvl;/usr/local/addons/hvl/node/bin/node /usr/local/addons/hvl/node/bin/npm install homematic-virtual-tradfridevice --production --prefix "/usr/local/addons/hvl"
/bin/sh: /usr/local/addons/hvl/node/bin/node: not found

    at checkExecSyncError (child_process.js:621:11)
    at Object.execSync (child_process.js:657:15)
    at Server.installNPM (/usr/local/addons/hvl/node_modules/homematic-virtual-interface/lib/Server.js:1439:30)
    at /usr/local/addons/hvl/node_modules/homematic-virtual-interface/lib/Server.js:1138:26
    at Array.some (<anonymous>)
    at /usr/local/addons/hvl/node_modules/homematic-virtual-interface/lib/Server.js:1133:18
    at Server.buildPluginList (/usr/local/addons/hvl/node_modules/homematic-virtual-interface/lib/Server.js:1208:13)
    at Server.fetchPluginList (/usr/local/addons/hvl/node_modules/homematic-virtual-interface/lib/Server.js:1186:14)
    at Server.installPlugin (/usr/local/addons/hvl/node_modules/homematic-virtual-interface/lib/Server.js:1131:10)
    at Server.handleConfigurationRequest (/usr/local/addons/hvl/node_modules/homematic-virtual-interface/lib/Server.js:618:26)
Sat Feb 01 2020 15:25:03 GMT+0100 (CET)[Homematic Virtual Interface.Server] [INFO] - Installing homematic-virtual-tradfridevice to /usr/local/addons/hvl
Sat Feb 01 2020 15:22:30 GMT+0100 (CET)[HomematicLogicalLayer] [INFO] - nothing found
Sat Feb 01 2020 15:22:30 GMT+0100 (CET)[HomematicLogicalLayer] [INFO] - looking for corpses
Sat Feb 01 2020 15:21:30 GMT+0100 (CET)[Logging System] [INFO] - 0 Logentries removed
Sat Feb 01 2020 15:21:30 GMT+0100 (CET)[Homematic Virtual Interface.Server] [INFO] - CCU is alive
Sat Feb 01 2020 15:21:30 GMT+0100 (CET)[HomematicLogicalLayer] [INFO] - CCU InterfaceList [{"name":"BidCos-RF"},{"name":"VirtualDevices"},{"name":"HmIP-RF"},{"name":"HVL"},{"name":"hmvirtual"}]
Sat Feb 01 2020 15:21:30 GMT+0100 (CET)[ConfigurationServer] [INFO] - Configuration Server is listening on: Port 8300
Sat Feb 01 2020 15:21:30 GMT+0100 (CET)[Homematic Virtual Interface.Server] [WARN] - No plugins found. See the README for information on installing plugins.
Sat Feb 01 2020 15:21:29 GMT+0100 (CET)[Homematic Virtual Interface.Server] [INFO] - Reload .. shutdown all plugins
Sat Feb 01 2020 15:21:29 GMT+0100 (CET)[HomematicLogicalLayer] [INFO] - CCU RPC message timeout set to 300000 ms
Sat Feb 01 2020 15:21:29 GMT+0100 (CET)[HomematicLogicalLayer] [INFO] - XML-RPC server for interface Homematic Virtual Interface is listening on 127.0.0.1:8301
Sat Feb 01 2020 15:21:29 GMT+0100 (CET)[Config] [INFO] - MyIP is 127.0.0.1
Sat Feb 01 2020 15:21:29 GMT+0100 (CET)[HomematicLogicalLayer] [INFO] - init stored consumer with host 192.168.178.44 at port 1999 path /
Sat Feb 01 2020 15:21:29 GMT+0100 (CET)[HomematicLogicalLayer] [INFO] - init consumer {"hostname":"127.0.0.1","port":"1999","path":"/","callbackid":"1511"}
Sat Feb 01 2020 15:21:29 GMT+0100 (CET)[HomematicLogicalLayer] [INFO] - init stored consumer with host 192.168.178.44 at port 9292 path /bidcos
Sat Feb 01 2020 15:21:29 GMT+0100 (CET)[HomematicLogicalLayer] [INFO] - init consumer {"hostname":"127.0.0.1","port":"9292","path":"/bidcos","callbackid":"HVL_java"}
Sat Feb 01 2020 15:21:29 GMT+0100 (CET)[HomematicLogicalLayer] [INFO] - Welcome. will create a interface layer for CCU at 192.168.178.44
Sat Feb 01 2020 15:21:29 GMT+0100 (CET)[Homematic Virtual Interface.Server] [INFO] - Trying to load Localization from /usr/local/addons/hvl/node_modules/homematic-virtual-interface/lib/Localizable.strings
Sat Feb 01 2020 15:21:29 GMT+0100 (CET)[Homematic Virtual Interface.Server] [INFO] - starting point was /usr/local/addons/hvl/node_modules/homematic-virtual-interface/lib
Sat Feb 01 2020 15:21:29 GMT+0100 (CET)[Homematic Virtual Interface.Server] [INFO] - hello from the flight deck. my path is /usr/local/addons/hvl/node_modules/homematic-virtual-interface
Sat Feb 01 2020 15:21:29 GMT+0100 (CET)[Homematic Virtual Interface.Server] [INFO] - current system user is root
Sat Feb 01 2020 15:21:29 GMT+0100 (CET)[Homematic Virtual Interface.Server] [INFO] - running on linux with node version v12.14.0
Sat Feb 01 2020 15:21:29 GMT+0100 (CET)[Homematic Virtual Interface.Server] [INFO] - core version 0.2.75
Sat Feb 01 2020 15:21:29 GMT+0100 (CET)[Config] [INFO] - try to load config : /usr/local/etc/config/hvl//config.json
Sat Feb 01 2020 15:21:29 GMT+0100 (CET)[Logging System] [INFO] - Will remove logentries older than Sat Feb 01 2020 10:21:29 GMT+0100 (CET)
Sat Feb 01 2020 15:21:29 GMT+0100 (CET)[Core] [INFO] - Launching

**Comment by thkl** [comment]
bitte mal einen blick auf die config.json in /usr/local/etc/config/hvl//config.json werfen.

Wenn da noch: 
`"npm_command":"ADDON_DIR/node/bin/node ADDON_DIR/node/bin/npm"`
steht muss das in 

`"npm_command":"npm"`

geändert werden.

**Comment by K3vb3rt** [comment]
Das war es, danke. Jetzt lassen sie sich installieren, aber nicht starten.

`Sat Feb 01 2020 21:07:23 GMT+0100 (CET)[Homematic Virtual Interface.Server] [INFO] - Reload .. shutdown all plugins
Sat Feb 01 2020 21:07:23 GMT+0100 (CET)[Homematic Virtual Interface.Server] [INFO] - Have to build new entry for homematic-virtual-tradfridevice
Sat Feb 01 2020 21:07:12 GMT+0100 (CET)[Homematic Virtual Interface.Server] [ERROR] - Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:427:19)
    at writeOrBuffer (_stream_writable.js:415:5)
    at Socket.Writable.write (_stream_writable.js:305:11)
    at Object.execSync (child_process.js:655:20)
    at Server.installNPM (/usr/local/addons/hvl/node_modules/homematic-virtual-interface/lib/Server.js:1439:30)
    at /usr/local/addons/hvl/node_modules/homematic-virtual-interface/lib/Server.js:1138:26
    at Array.some (<anonymous>)
    at /usr/local/addons/hvl/node_modules/homematic-virtual-interface/lib/Server.js:1133:18
    at Server.buildPluginList (/usr/local/addons/hvl/node_modules/homematic-virtual-interface/lib/Server.js:1208:13)
    at Server.fetchPluginList (/usr/local/addons/hvl/node_modules/homematic-virtual-interface/lib/Server.js:1186:14)
Sat Feb 01 2020 21:06:42 GMT+0100 (CET)[Homematic Virtual Interface.Server] [INFO] - Installing homematic-virtual-tradfridevice to /usr/local/addons/hvl
Sat Feb 01 2020 21:05:34 GMT+0100 (CET)[Homematic Virtual Interface.Server] [INFO] - Reload .. shutdown all plugins
Sat Feb 01 2020 21:05:34 GMT+0100 (CET)[Homematic Virtual Interface.Server] [INFO] - Found homematic-virtual-harmonydevice set disable to false
Sat Feb 01 2020 21:04:58 GMT+0100 (CET)[Homematic Virtual Interface.Server] [INFO] - Reload .. shutdown all plugins
Sat Feb 01 2020 21:04:58 GMT+0100 (CET)[Homematic Virtual Interface.Server] [INFO] - Have to build new entry for homematic-virtual-harmonydevice
Sat Feb 01 2020 21:04:17 GMT+0100 (CET)[HomematicLogicalLayer] [INFO] - nothing found
Sat Feb 01 2020 21:04:17 GMT+0100 (CET)[HomematicLogicalLayer] [INFO] - looking for corpses
Sat Feb 01 2020 21:04:04 GMT+0100 (CET)[Homematic Virtual Interface.Server] [ERROR] - Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:150:25)
    at writeGeneric (internal/stream_base_commons.js:141:3)
    at Socket._writeGeneric (net.js:771:11)
    at Socket._write (net.js:783:8)
    at doWrite (_stream_writable.js:431:12)
    at writeOrBuffer (_stream_writable.js:415:5)
    at Socket.Writable.write (_stream_writable.js:305:11)
    at Object.execSync (child_process.js:655:20)
    at Server.installNPM (/usr/local/addons/hvl/node_modules/homematic-virtual-interface/lib/Server.js:1439:30)
    at /usr/local/addons/hvl/node_modules/homematic-virtual-interface/lib/Server.js:1138:26
Sat Feb 01 2020 21:03:36 GMT+0100 (CET)[Homematic Virtual Interface.Server] [INFO] - Installing homematic-virtual-harmonydevice to /usr/local/addons/hvl
Sat Feb 01 2020 21:03:18 GMT+0100 (CET)[Logging System] [INFO] - 0 Logentries removed
Sat Feb 01 2020 21:03:17 GMT+0100 (CET)[Homematic Virtual Interface.Server] [INFO] - CCU is alive
Sat Feb 01 2020 21:03:17 GMT+0100 (CET)[HomematicLogicalLayer] [INFO] - CCU InterfaceList [{"name":"BidCos-RF"},{"name":"VirtualDevices"},{"name":"HmIP-RF"},{"name":"HVL"},{"name":"hmvirtual"}]
Sat Feb 01 2020 21:03:17 GMT+0100 (CET)[ConfigurationServer] [INFO] - Configuration Server is listening on: Port 8300
Sat Feb 01 2020 21:03:17 GMT+0100 (CET)[Homematic Virtual Interface.Server] [WARN] - No plugins found. See the README for information on installing plugins.
Sat Feb 01 2020 21:03:17 GMT+0100 (CET)[Homematic Virtual Interface.Server] [INFO] - Reload .. shutdown all plugins
Sat Feb 01 2020 21:03:17 GMT+0100 (CET)[HomematicLogicalLayer] [INFO] - CCU RPC message timeout set to 300000 ms
Sat Feb 01 2020 21:03:17 GMT+0100 (CET)[HomematicLogicalLayer] [INFO] - XML-RPC server for interface Homematic Virtual Interface is listening on 127.0.0.1:8301
Sat Feb 01 2020 21:03:17 GMT+0100 (CET)[Config] [INFO] - MyIP is 127.0.0.1
Sat Feb 01 2020 21:03:17 GMT+0100 (CET)[HomematicLogicalLayer] [INFO] - init stored consumer with host 192.168.178.44 at port 1999 path /
Sat Feb 01 2020 21:03:17 GMT+0100 (CET)[HomematicLogicalLayer] [INFO] - init consumer {"hostname":"192.168.178.44","port":"1999","path":"/","callbackid":"1511"}
Sat Feb 01 2020 21:03:17 GMT+0100 (CET)[HomematicLogicalLayer] [INFO] - init stored consumer with host 192.168.178.44 at port 9292 path /bidcos
Sat Feb 01 2020 21:03:17 GMT+0100 (CET)[HomematicLogicalLayer] [INFO] - init consumer {"hostname":"192.168.178.44","port":"9292","path":"/bidcos","callbackid":"HVL_java"}
Sat Feb 01 2020 21:03:17 GMT+0100 (CET)[HomematicLogicalLayer] [INFO] - Welcome. will create a interface layer for CCU at 192.168.178.44
Sat Feb 01 2020 21:03:17 GMT+0100 (CET)[Homematic Virtual Interface.Server] [INFO] - Trying to load Localization from /usr/local/addons/hvl/node_modules/homematic-virtual-interface/lib/Localizable.strings
Sat Feb 01 2020 21:03:17 GMT+0100 (CET)[Homematic Virtual Interface.Server] [INFO] - starting point was /usr/local/addons/hvl/node_modules/homematic-virtual-interface/lib
Sat Feb 01 2020 21:03:17 GMT+0100 (CET)[Homematic Virtual Interface.Server] [INFO] - hello from the flight deck. my path is /usr/local/addons/hvl/node_modules/homematic-virtual-interface
Sat Feb 01 2020 21:03:17 GMT+0100 (CET)[Homematic Virtual Interface.Server] [INFO] - current system user is root
Sat Feb 01 2020 21:03:17 GMT+0100 (CET)[Homematic Virtual Interface.Server] [INFO] - running on linux with node version v12.14.0
Sat Feb 01 2020 21:03:17 GMT+0100 (CET)[Homematic Virtual Interface.Server] [INFO] - core version 0.2.75
Sat Feb 01 2020 21:03:17 GMT+0100 (CET)[Config] [INFO] - try to load config : /usr/local/etc/config/hvl//config.json
Sat Feb 01 2020 21:03:17 GMT+0100 (CET)[Logging System] [INFO] - Will remove logentries older than Sat Feb 01 2020 16:03:17 GMT+0100 (CET)
Sat Feb 01 2020 21:03:16 GMT+0100 (CET)[Core] [INFO] - Launching
`

**Comment by thkl** [comment]
HVL zur Not einmal Neustarten.

**Comment by K3vb3rt** [comment]
Das war es, danke! Jetzt muss ich nur mit der Konfiguration klarkommen :-D
