### ISSUE TITLE
Sonos Geräte werden nicht mehr auf der CCU angelegt

### ISSUE THREAD

**Issue by ajscat** [thkl/Homematic-Virtual-Interface#102]
Sorry, ich habe das jetzt nochmal als eigenes Problem angelegt. Gefunden werden diese ja wieder problemlos!! Vielen Dank dafür!!!!

Neue Geräte landen nicht im Eingang auf der CCU.

**Comment by ajscat** [comment]
Auf einer frischen Raspberrymatic Installation funktioniert es. :-(. An was könnte das liegen? Für eine Idee wäre ich sehr dankbar

**Comment by ajscat** [comment]
Auf der Raspberrymatic stehen unter CCU info 2 Verbindungen und auf dem Rapberry -->CCU2 eine Verbindung

**Comment by ajscat** [comment]
OK! Daran lag es. Wie das zustande kommt...keine Ahnung. Hab aus einer Sicherung einen Teil der persist.json kopiert. Danach hat es wieder funktioniert.

**Comment by etw16** [comment]
Ich habe genau dieses Problem auch. Kannst Du mir genauer erklären wie Du vorgegangen bist, um dieses zu beheben? Vielen Dank im Voraus!

**Comment by ajscat** [comment]
Hallo,

hast du ein etwas älteres Backup?

die Datei persist.json sollte ungefähr so aussehen:

{
  "consumer": "[{\"hostname\":\“XXX.XXX.XX.XX\",\"port\":\"1999\",\"path\":\"/\",\"callbackid\":\"2803\"},{\"hostname\":\"XXX.XXX.XX.XX\",\"port\":\"9292\",\"path\":\"/bidcos\",\"callbackid\":\"HVL_java\"}]"
}

Falls nicht kannst du entweder aus dem Backup eine kopieren oder diese als Vorlage nehmen.

VG

**Comment by thkl** [comment]
Die persist Datei enthält die IDs unter der Rega von der CCU die Schnittstelle anspricht. Diese ändern sich mit jedem Reboot der CCU. Die sollte nicht einfach hin und her kopiert werden. Sonst redet die Schnittstelle mit der falschen Id und wird von Rega ignoriert. Reboot der CCU hilft in den Fällen denn dann fragt Rega mit einer neuen Id an.

**Comment by ajscat** [comment]
Genau das hat bei mir nicht funktioniert. Und daher habe ich eine ältere aus einem Backup verwendet.

**Comment by etw16** [comment]
Hallo zusammen,
ich habe die CCU ca. 5 mal neugestartet und keinen Erfolg gehabt. Neuinstallation brachte auch keinen Erfolg. Altes Backup einspielen ebenfalls nicht. 

Dann bin ich einfach hingegangen und habe das HVL Add-On deinstalliert. Dann einen Neustart und danach per FTP alles von der CCU gelöscht, was irgendwie HVL im Namen hatte.  Dann das Add-On neu installiert, CCU gestartet und siehe da...alles super.

Viele Grüße
Max
