### ISSUE TITLE
Events für Update auf HomeBrdige

### ISSUE THREAD

**Issue by JensBonse** [thkl/Homematic-Virtual-Interface#109]
Hallo Thomas,

wäre es möglich auch einen Update Trigger für HVL zu bauen, wie ich bereits für CUxD angefragt habe und wie es schon Home Matic Variablen gibt.
Hintergrund ist folgender:
Lampen die an der Hue Bridge angemeldet sind, aber nicht direkt von Philips sind, werden nicht nach HomeKit durchgereicht. Daher habe ich die Lampe per HVL nach HomeMatic gebracht und von HomeMatic über die HomeBridge nach HomeKit. Wenn ich nun in HomeMatic oder der Hue App eine Änderung an der Lampe mache (dimmen), dann Bekommt das Home Matic und Hue jeweils mit. In HomeKit bleibt der Status jedoch unverändert.

Wird vermutlich das gleiche Problem sein, das dort kein Event getriggert wird, welche HomeKit dann als Update mitbekommt.
Mit dem Update Trigger könnte man das dann quasi abfangen und HomeBridge dazu bringen die aktulaisierten daten zu pullen.

**Comment by thkl** [comment]
Kann ich machen ich verhalte mich da wie ein normales Interface

**Comment by thkl** [comment]
Ich mache den hier mal zu, denn der Issue gehört zum homebridge Projekt.
Dort wird es aber in der nächsten Version möglich sein, beliebige XMLRPC Interfaces hinzuzufügen.
