### ISSUE TITLE
Download Link funktioniert nicht

### ISSUE THREAD

**Issue by sebastianlorenzen** [thkl/Homematic-Virtual-Interface#117]
https://github.com/thkl/Homematic-Virtual-Interface/blob/master/raspberrymatic_installer/hvl-raspb-0.0.2.tar.gz

führt ins leere... 404

**Comment by thkl** [comment]
https://github.com/thkl/Homematic-Virtual-Interface/blob/master/raspberrymatic_installer/hvl-raspb-0.0.10.tar.gz

**Comment by sebastianlorenzen** [comment]
Auf dieser Seite ist der Link nicht aktuell: https://github.com/thkl/Homematic-Virtual-Interface/tree/master/raspberrymatic_installer

**Comment by thkl** [comment]
Ahh in der Readme ok 😉
