### ISSUE TITLE
Nanoleaf Aurora multiple Instanzen

### ISSUE THREAD

**Issue by JensBonse** [thkl/Homematic-Virtual-Interface#12]
Hi!

Könntest du es so machen, dass man mehrere Auroras konfigurieren kann?
Bisher kann man leider nur eine konfigurieren.

**Comment by thkl** [comment]
woran erkenne ich denn mehrere Lampen ? Haben die dann eine neue IP im Netz ?

**Comment by JensBonse** [comment]
Ja, jede Aurora hat ihren eigenen Controller und ihre eigene IP.
