### ISSUE TITLE
RaspberryMatic HVL Addon - manche Plugins (Alexa, BMW, Flower, PhilipsTV, ..) nicht zu sehen

### ISSUE THREAD

**Issue by steckenpferd** [thkl/Homematic-Virtual-Interface#123]
@thkl Habe für RaspberryMatic die aktuelleste HVL Addon Version installiert aber manche Addons sind nicht zu sehen - warum ist das so? Es fehlen:
- Alexa
- BMW Connect
- Dummy
- Flower
- Logging
- PhilipsTV

**Comment by thkl** [comment]
die aktuell nutzbaren Plugins stehen hier https://github.com/thkl/Homematic-Virtual-Interface/blob/master/plugins/plugins.json daher wird auch die Liste erzeugt.

Alexa ist deprecated
BMW Connect war nicht fertig ;)
Dummy ist nur ein Dummy
FlowerPower ist auch nicht fertig (wird es auch nicht weil das Produkt von Parrot eingestellt wurde)
Logging ist nur ein test für mich 
PhilipsTV steuert die LEDs des Amiblight was aber auch nicht mehr von aktueller Firmware des TV unterstützt wird
