### ISSUE TITLE
HVL schmiert permanent ab

### ISSUE THREAD

**Issue by MathiasH82** [thkl/Homematic-Virtual-Interface#13]
Hallo Herr Kluge, 

ich bin hier gerade völlig am verzweifeln und möglicherweise können Sie mir weiterhelfen. 

Ich betreibe einen RaspberryMatic 2.29.23.20171022 und bekomme das Addon HVL einfach nicht zum laufen. 

Ich habe mir hvl-raspb-0.0.7.tar.gz geladen und auf dem RaspberryMatic (über Systemsteuerung/ZusatzSoftware) installiert und kann das hvl aber nicht einreichen. Versuche ich http://ip:8182 aufzurufen bekomme ich die Meldung dass der Server nicht antwortet. Zeitgleich erscheint in RaspberryMatic die Fehlermeldung „HVL Eine Komponente der HomematicZentrale reagiert nicht mehr“. 

Habe ich etwas übersehen? 

Beste Grüße, 
Mathias

**Comment by thkl** [comment]
Auf der RM ist das ein anderer Port. 
Nach der Installation des Addons und dem Neustart der RM werden erst alle notwendigen Komponenten installiert. Das dauert etwas. In der Systemsteuerung der RM WebOberfläche wird am Ende ein Button für HVL angelegt. Der führt zur WebOberfläche von HVL

**Comment by MathiasH82** [comment]
Stimmt, 8300 ist der RM Port, es hatte sich aber herausgestellt dass ich mir mehr oder weniger die RM mit dem Addon zerschossen habe. Ich hatte es versucht zu deinstallieren, bekam Meldungen wie „Success Failure“ und das HVL Addon war zwar in zusatzoftware nicht mehr aufgeführt aber es kamen nur noch am laufenden Band Fehlermeldungen dass das HVL Addon abgestürzt sei (welches ja eigentlich nicht mehr installiert war). 
Jetzt hab ich RM komplett neu aufgesetzt, alles neu angelernt und eingerichtet und nun funktioniert auch alles wieder :)
