### ISSUE TITLE
Abfrage der Lautstärke für DenonHTTP Plugin

### ISSUE THREAD

**Issue by HookHM** [thkl/Homematic-Virtual-Interface#140]
Hallo @thkl ,

funktioniert die Abfrage nicht weil es nicht implementiert ist, oder gibt es einen Fehler? Weil hier hast Du ja danach gefragt wie man die Lautstärke abfragt https://github.com/thkl/Homematic-Virtual-Interface/issues/137#issuecomment-748890256

Und im Plugin sieht man ja auch etwas davon: 
```  
getVolume () {
    let self = this
    let hmDevice = this.remotes[0]
    if (hmDevice) {
      let host = this.config.getValueForPlugin(this.name, 'host')
      this.log.info('Connecting to %s', host)
      let urlCommand = 'MV?'
      this.log.info('Command is %s', urlCommand)
      let responseData
      const options = {
        hostname: host,
        port: 8080,
        path: '/goform/formiPhoneAppDirect.xml?' + urlCommand,
        method: 'GET'
      }

```  

Könntest Du das noch unterstützen?

**Comment by thkl** [comment]
Genau ich sende das MV? Kommando und das was zurückkommt schreibe ich in TARGET_VOLUME des Channels 19 der ersten angelegten Denon Fernbedienung.

**Comment by HookHM** [comment]
Hmm, aber das ist leer:
<img width="1306" alt="Bildschirmfoto 2021-01-25 um 18 29 29" src="https://user-images.githubusercontent.com/55434236/105742057-534a0080-5f3b-11eb-9527-9ec744d97864.png">

Wie könnte ich es denn aus "TARGET_VOLUME des Channels 19" in eine SysVar schreiben?

**Comment by thkl** [comment]
hmm dann kommt da nichts vom Denon zurück ... aber das haben wir ja schon in dem vorherigen Ticket besprochen
Dann kannst du auch das "nichts" nicht in eine Variable schreiben

**Comment by HookHM** [comment]
Vielleicht geht das mit der Volume Abfrage nur per Telnet. Per URL bekomme ich auch nur eine weiße Seite.

**Comment by thkl** [comment]
tja dann haben wir es ja, wie schon in dem anderen Issue besprochen. Es geht nicht.

**Comment by HookHM** [comment]
Ich werde das nochmal in ruhe testen und mich dann nochmal melden. Danke erstmal.

**Comment by thkl** [comment]
Ich mach das jetzt hier zu. Damit ist das Denon Thema für mich beendet. Alles was technisch funktioniert, funktioniert. Die Lautstärke Abfrage funktioniert eben nicht. Aber das hatten wir alles schon.

**Comment by HookHM** [comment]
Okay dann lassen wir das. Wäre es sinnvoll die Abfrage wieder aus dem Code zu nehmen damit das nicht unnötig am Denon landet?
