### ISSUE TITLE
Wundergrund-/Openweather-Plugin

### ISSUE THREAD

**Issue by dehsgr** [thkl/Homematic-Virtual-Interface#16]
Hey, ich habe zwei Probleme (möglicherweise auch Fehlbedienungen), die ich gerne Kommunizieren möchte:

1. Wenn ich in der CCU die von o.g. Plugins angelegten Geräte lösche, so verschwinden diese nicht wirklich aus der CCU. Erst nach einem Reboot (der CCU) waren sie dann verschwunden.
2. Wird eines der o.g. Plugins wiederholt installiert, so werden die zugehörigen Variablen auf der CCU dupliziert.

**Comment by thkl** [comment]
Oh ok , ich schau mir das mal an . danke

**Comment by thkl** [comment]
Mahlzeit, 
ich hab mir beide Plugins mal angeschaut. Es werden vom Plugin selber, keine Variablen in der CCU angelegt. Diese werden durch ein CCU Script angelegt, welches beim "Fertig" Klick auf das Gerät im Posteingang erzeugt werden.

An der Stelle kann ich leider nichts machen. Wenn Geräte über die CCU gelöscht werden, wird ein Lösch-Befehl durch die CCU an HVL gesendet. Diesen beantworte ich normalerweise immer positiv (damit können auch Geräte, deren Plugins fehlen gelöscht werden)
