### ISSUE TITLE
unknow content type

### ISSUE THREAD

**Issue by coolsurfer** [thkl/Homematic-Virtual-Interface#17]
Nur ein LOG-Problem, aber einfach zu beheben :-)

[ConfigurationServer][WARN] unknow content type for /home/pi/node_modules/homematic-virtual-interface/www//assets/icons/favicon.ico this is a serious bug

**Comment by thkl** [comment]
ja ;)

**Comment by thkl** [comment]
should fixed in core 0.2.64
