### ISSUE TITLE
Mehrere Harmony Hubs

### ISSUE THREAD

**Issue by tom-from-bavaria** [thkl/Homematic-Virtual-Interface#18]
Ich habe im config.json eine 2. Harmony Bridge angelegt. Leider gibt es nur ein harmony_objects.json für die Tasten ohne Zuordnung zu der jeweiligen Bridge. Dadurch überschreiben sich die Änderungen gegenseitig.
Auch werden die devices nur angelegt wenn nur eine Bridge konfiguriert ist.
Bei den Hue funktioniert es auf diese Art mehrere Hubs anzulegen.

**Comment by thkl** [comment]
Hatte ich bisher nicht vorgesehen. 
Da müsste ich einiges umbauen.

**Comment by tom-from-bavaria** [comment]
Wäre super wenn das ginge, kann mir nicht vorstellen das ich der einzige mit mehreren Harmony bin.
Im Prinzip funktioniert es ja mit dem Workaround, ich bekomme halt an beiden Harmony alle Lampen zur Auswahl und kann auch alles schalten, sauberer wäre aber das getrennt einrichten zu können.
Generellere es schön wenn man die plugins ohne das json zu editieren mehrfach im UI anlegen könnte.

**Comment by thkl** [comment]
Ja, geht alles ist halt nur Arbeit :)

**Comment by DerChecker** [comment]
Hallo zusammen, das ist mein erster Post hier.

@thkl: Erstmal Hochachtung vor der Arbeit und vielen Dank dafür! Habe meine ersten 3 Hue-Lampen mit Hilfe von HVI über einen 6-Fach Homematic Taster zum Ein-und Ausschalten bekommen.

@tom-from-bavaria: Sie sind nicht nicht allein. Ich habe sogar 3 HArmony Hubs, aber zur Zeit (zumindest noch) "nur" 2 Stück in Benutzung.

Habe auf meiner Raspberrymatic das HUE-Plugin über die HVI installiert und möchte das Ganze später mit Alexa und/oder Googele HomeSteuern. Momentan ein Wirwarr von Möglickeiten, Gateways und Variablen, die sich hin und her aktualisieren. Da kommt doch so eine Lösung hier wie gerufen, wenn denn alles funktioniert. Raumfeld habe ich auch und zwar 10 Geräte. werde ich mal testen.

**Comment by DerChecker** [comment]
Meine Raumfeld Geräte habe ich über die CCU bisher leider nicht zum laufen bekommen.

**Comment by DerChecker** [comment]
Warum denn geschlossen? Wird nicht mehr weiter entwickelt?

**Comment by thkl** [comment]
Es gibt einen neueren Issue hierfür

**Comment by DerChecker** [comment]
👍
