### ISSUE TITLE
LIB-Pfad falsch

### ISSUE THREAD

**Issue by coolsurfer** [thkl/Homematic-Virtual-Interface#2]
In einigen Dateien wird folgendes genutzt um den Pfad zu bereinigen
**if (appRoot.endsWith('node_modules/daemonize2/lib')) {appRoot =  appRoot+'/../../../lib'}**

Das kann nicht funktionieren; richtig könnte es so aussehen:
if (appRoot.endsWith("node_modules/daemonize2/lib")) {appRoot = appRoot+"/../../homematic-virtual-interface/lib";}

Oder hab ich dabei was übersehen, weil mit der ersten (falschen) Zeile und dem Start als Daemon erscheinen nur Fehler. Geändert hab ich es lokal in folgenden Dateien:

homematic-virtual-ccudutycylcle/CCUDutyCycle.js
homematic-virtual-huedevice/HuePlatform.js
homematic-virtual-interface/lib/logger.js
homematic-virtual-interface/lib/Server.js

**Comment by thkl** [comment]
jain, das ganze ist abhängig, wie das System installiert bzw. gestartet wird. Wenn das System aus dem github geladen wird dann ist path/lib der root ... wenn man es als npm modul installiert $home/node_modules/homematic-virtual-interface/lib 

Aber stimmt, das ganze könnte man hübscher machen und auch in ein eigenes util.js etc auslagern ...

**Comment by thkl** [comment]
sollte ab core 0.0.43 funktionieren
