### ISSUE TITLE
Unhandled Rejection at: Promise

### ISSUE THREAD

**Issue by dupan99** [thkl/Homematic-Virtual-Interface#20]
I got a lot of these error messages after a reboot.

[Homematic Virtual Interface.Server] [ERROR] - Unhandled Rejection at: Promise

**Comment by thkl** [comment]
That’s an internal error. I have to extend the logger to show the root cause of that error. At this time there is nothing you can do to fix this.

**Comment by thkl** [comment]
0.2.65 (not yed released) adds more info about the missing rejection handler
