### ISSUE TITLE
...2. Hue Bridge...?

### ISSUE THREAD

**Issue by Kraehe1806** [thkl/Homematic-Virtual-Interface#21]
...denke, mehre User habe mehr als eine Hue Bridge im Haushalt. Ist es möglich eine zweite Bridge mit anderer IP einzubinden???

**Comment by thkl** [comment]
Es könnte mit einem manuellen 2. Config.json Eintrag funktionieren:

```
{
      "type": "homematic-virtual-huedevice",
      "name": "Hue_2",
      "instance": 2
}
```

Wichtig ist, der Eintrag name muss sich von der ersten Bridge unterscheiden. An diesem orientieren sich alle Funktionen, die in und aus dem config File lesen/schreiben. Und der Eintrag "instance":2 muss hinzugefügt werden.

Dann sollte es gehen ... (hab es aber mangels 2. Bridge nie getestet)

**Comment by Kraehe1806** [comment]
Erstmal Danke für die schnelle Antwort...
...hmmm....wo meinst Du denn????
Habe die config.json nur in  "/usr/local/addons/hvl/node_modules/daemonize2/examples/advanced"

Da steht aber nix drin.....??? Bzw. habe den Eintrag dort reingesetzt....aber im WebView sehe ich dann nix...

**Comment by thkl** [comment]
liegt in /home/pi/.hm_virtual_interface

**Comment by Kraehe1806** [comment]
...sorry....nutze das RaspberryMatic addon - da ist kein home/pi?

**Comment by thkl** [comment]
opps hätte ich sehen können .. aber ok auf der RM liegt der config Folder hier /usr/local/etc/config/hvl/

**Comment by Kraehe1806** [comment]
...funktioniert leider nicht mit dem 2. Eintrag ala
`{
      "type": "homematic-virtual-huedevice",
      "name": "Hue_2",
      "instance": 2,
      "disabled": false,
      "hue_bridge_ip": "192.168.xxx.xxx",
      "hue_username": "9icv3Kl9mTXOxxxxxxxxxxxxxxxxxx",
      "refresh": "60"

}
`
....Wenn ich den einfüge, habe ich keinen Web Verbindung mehr auf die Configurationssseite...

**Comment by thkl** [comment]
Schau mal bitte, ob Deine neu erzeugte config.json ein valides json Format hat (zb in jsonlint.com einkippen)

**Comment by Kraehe1806** [comment]
...danke für den Tipp...war ein Kommafehler.....

Habe jetzt in der Navigation einen 2. Hue Eintrag....klicke ich den jedoch an, werden mir die Lampen der ersten HueBridge angezeigt...

![hvl hue](https://user-images.githubusercontent.com/34195426/34357863-dab01398-ea4a-11e7-8b75-7bd5426da84f.png)

P.S.: Frohe Weihnachten

**Comment by thkl** [comment]
Das ist ein Anfängerfehler im Handling der Config Web Requests .. Workaround der gehen sollte, benenne mal Hue_2 in 2_Hue um ...

**Comment by Kraehe1806** [comment]
...WUNDERBAR....WUNDERBAR....WUNDERBAR.....noch ein Weihnachtsgeschenk am 2. Feiertag....es läuft!!!
Vielen Dank für Deine Mühe...

Nur eine Frage hätte ich noch:
Wenn ich bei einer Hue, die als Gerät in der CCU (Generiere homematic device) schon eingebunden war, nochmal auf "Generiere homematic devices" gehe, weil sich vielleicht Änderungen ergeben haben, schmeißt er mir immer die schon aktiven Gruppen und Scenen raus und ich muss sie über den Posteingang wieder hinzufügen....und natürlich bei allen Programmen, wo sie mal verwendet wurden.

Ist das so gewollt oder mein Handling einfach falsch???

**Comment by thkl** [comment]
das ist aktuell leider so, auch ne Sache die ich mal angehen müsste

**Comment by Kraehe1806** [comment]
...Trotzdem....ein Problem behoben...schönen Feiertag noch....(ich close mal)
