### ISSUE TITLE
Interface-Prozess 'VirtualDevices' läuft nicht.

### ISSUE THREAD

**Issue by JensBonse** [thkl/Homematic-Virtual-Interface#22]
Hi!

Seit neustem schmiert VirtualDevices ab. Wenn ich HVL deinstalliere läuft die CCU und VirtualDevices einwandfrei.
Wenn ich es erneut installiere (1. reboot) und ich dann die IP von HVL eintrage funktioniert alles.
Boote ich dann erneut, schmiert VirtualDevices ab.
Habe das HVL 0.5 addon installiert. CCU FW ist 2.27.8 auf YAHM 1.8

**Comment by JensBonse** [comment]
Bin jetzt schon weiter.
Selbst wenn ich HVL von der CCU deinstalliert habe, kann ich die Devices die Über HVL kommen immer noch steuern.

In der /usr/local/etc/config/InterfacesList.xml steht HVL nicht drin.
In der /etc/config_templates/InterfacesList.xml steht HVL nicht drin.
Gibt es sonst noch eine InterfacesList.xml?

**Comment by guybrushix** [comment]
Hi,
Ich habe nach dem zweiten Reboot auch das Problem das Virtual Devices abschmiert. Nach langen ausprobieren hab ich jetzt entdeckt, das sobald ich die S59hvl aus /etc/init.d lösche funktioniert alles auch nach mehrmaligen Rebooten. Die Datei soll beim Start die InterfacesList.xml angleichen. Doch scheinbar reicht einmal vollkommen und eine weitere Änderung lässt die Virtual Devices abstürzen.

Ich hoffe das hilft

**Comment by JensBonse** [comment]
Habe auch die S59hvl und alle damit in Verbindung stehenden Dateien aus der CCU gelöscht.
In den oben genannten XML Dateien ist auch keine Spur mehr von HVL enthalten. Trotzdem sind alle über HVL eingebunden Geräte über die CCU steuerbar, obwohl das Interface nicht mehr definiert wird.

**Comment by bvol** [comment]
@thkl Irgendwas ist komisch. Wenn ich z.B. das Netatmo Plugin aktiviert habe und die Raspberrymatic neu starte, schmieren mir die virtualdevices ab. Wenn ich das Plugin deaktiviere, den Raspberrymatic neu starte und das Plugin erst nachträglich aktiviere, ist alles schick.

Mein Workarround zu dem Thema ist nun, dass ich HVL direkt auf dem Raspberrymatic laufen lasse und statt S51hvl nun HVL via S99hvl starte. Dann kann ich die Plugins aktiv lassen, virtualdevices sind verfügbar und die Netatmo Devices werden nach einer kurzen Verzögerung dann auch auf dem Raspberrymatic angezeigt.

**Comment by bvol** [comment]
@MatzeFro : Auf was zeigt Deine S59hvl? Eventuell ins leere? Meiner Meinung nach kannst Du die einfach löschen. 

Zeig mal den Inhalt von /usr/local/etc/config/hvl/config.json

Und klar, wie hast Du installiert? Wie hast Du die Interfaces.xml konfiguriert? Manuell oder mit dem Addon?

**Comment by MatzeFro** [comment]
@bvol : 
S51hvl -> /usr/local/etc/config/rc.d/hvl
genau wie die
S99hvl -> /usr/local/etc/config/rc.d/hvl

wenn ich die S51hvl lösche kommt sie aber immer wieder (nach reboot)

in der config.json habe ich das nun auch auf S99hvl angepasst
[config.json.txt](https://github.com/thkl/Homematic-Virtual-Interface/files/2886261/config.json.txt)

du meinst die /usr/local/etc/config/InterfacesList.xml ? = nach meiner Erinnerung: automatisch

**Comment by bvol** [comment]
@MatzeFro hast Du eventuell noch ein $HVLDIR/etc/postinstall.sh (/usr/local/addons/hvl/etc/postinstall.sh) Script, dass Dir ln für S59 wieder generiert? Das Script wird (wenn vorhanden) aus der hvl raus gestartet. Wenn da nun der iink wieder generiert wird, wäre das Verhalten nach dem Reboot erklärbar. ich hab' auf meinem rasperrymatic kein solches Script.

**Comment by MatzeFro** [comment]
@bvol ja die Datei ist vorhanden. Ich habe sie einmla umbenannt aber das hat nichts verändert. S51hvl war trotzdem wieder da.
werde wohl mal ein Script bauen der die S51hvl regelmäßig auf vorhandesein prüft und ggf löscht.
