### ISSUE TITLE
TRADFRI E27 Lampen lassen sich nicht mehr ausschalten

### ISSUE THREAD

**Issue by YaGuwt** [thkl/Homematic-Virtual-Interface#25]
Seit dem Update auf das Tradfri Plugin 0.0.19 funktioniert das Ausschalten der Lampen (setzen von 0%) nicht mehr. Habe zwei unterschiedliche Typen (TRADFRI bulb E27 WS opal 980lm / W opal 1000lm) im Einsatz - bei beiden das gleiche Problem. Das Einschalten bzw. das Ändern der Helligkeit klappt problemlos. Aber sobald der Wert auf 0% gesetzt wird passiert nichts mehr. Dies war bisher jedoch problemlos möglich.

**Comment by thkl** [comment]
;o( ... ich schau mir das an

**Comment by thkl** [comment]
Das Tradfri Plugin wurde inzwischen komplett von https://github.com/mploetne überarbeitet. Bei mir funktioniert das mit dem Ausschalten.

**Comment by YaGuwt** [comment]
Hallo Thomas,

bin inzwischen auch weiter gekommen. Das Problem tritt nur nach einem 
Neustart des Raspberry auf. Wenn ich jedoch danach nochmal auf die Seite 
vom HVL Plugin gehe und dort auf Reboot geht es bei mir auch wieder. Bis 
zum nächsten Neustart. Da ich aber praktisch nie neustarten muss ist das 
kein Problem.

Vielen Dank und viele Grüße
Daniel

Am 2018-03-06 22:21, schrieb Thomas Kluge:
