### ISSUE TITLE
Google Home/Chromecast support

### ISSUE THREAD

**Issue by comtel2000** [thkl/Homematic-Virtual-Interface#29]
I guess the Google Cast would be a really good plugin candidate for a mapping to HM-OU-CFM-TW (Homematic mp3  Funk Gong)?
There are two good nodejs libs available:
https://github.com/noelportugal/google-home-notifier
https://github.com/thibauts/node-castv2-client

**Comment by thkl** [comment]
Feel free to build that :)

**Comment by comtel2000** [comment]
Mission accepted :)

**Comment by comtel2000** [comment]
Is there a (more or less) easy way to build and test the plugin offline without CCU? ..RaspPi with Raspmatic..?

**Comment by thkl** [comment]
you can use https://github.com/leonsio/YAHM ... it runs a ccu in a virtual container on a raspberry pi ... 
so you can run that ccu on the same pi as the hvl and debug that in a nice way ...

**Comment by comtel2000** [comment]
I'm just struggling with dependencies of google-home-notifier -> node-gyp, which requires Python.. So Python can be run on [RaspberryMatic] (https://github.com/jens-maus/RaspberryMatic) but not on limited CCU hardware. What do you thing?

**Comment by thkl** [comment]
no problem, cause HVL will not run on a real CCU device. So python may not be a problem

**Comment by comtel2000** [comment]
my first [GoogleCast plugin](https://github.com/comtel2000/Homematic-Virtual-Interface/tree/master/plugins/GoogleCast) is ready for beta testing. Is there a plan for external plugin sources?

**Comment by thkl** [comment]
The Plugin has to be published at npmjs so the installation works with npm i .... 

And there is a entry needed at plugins/plugins.json in the main repository. So you may publish your plugin and send me a pull request for the catalog file. At this point the plugin is visible to all users.

**Comment by thkl** [comment]
Ok i merged it.  The user has to manually refresh the plugin list by pressing the refresh button. After a short reload and cache update your plugin will appear in the list. 

👍

**Comment by comtel2000** [comment]
👍 thx
