### ISSUE TITLE
PID-File konfigurierbar

### ISSUE THREAD

**Issue by coolsurfer** [thkl/Homematic-Virtual-Interface#3]
Es wäre perfekt, wenn der Pfad des PID-Files nicht fest in homematic-virtual-interface/bin/hmviservice stehen würde, sondern über die ohnehin vorhandene config festgelegt werden könnte.

**Comment by thkl** [comment]
ja ;o) .. aber auch hier kommt es drauf an. man kann das ganze ja auch außerhalb des daemonziers starten (über /etc/init.d) und da legt dieses launch file das pid fest. Aber ja ;o)
