### ISSUE TITLE
Hue-Plugin

### ISSUE THREAD

**Issue by DerChecker** [thkl/Homematic-Virtual-Interface#31]
Hallo thkl,

gibt es eine Möglichkeit eine Hue-Lampe mit anderen Farbwerten (Weisswerten) zu starten? Leider kann man in der Raspberrymatic nur von werten zwischen 0 und 255 wählen. Hue bietet ja weitaus mehr. 

Des Weiteren würde ich die Hue Lampen gerne jeweils mit einem langen Tastendruck hochdimmen und mit einem langen Tastendruck wieder runter dimmen. Gibt es hier eine Möglichkeit das zu implementieren?
Ich hab schon irgendwie alle Einstellungen durch. 

Vielen Dank schon mal im Vorfeld und Weihnachtliche Grüße

**Comment by thkl** [comment]
In den Einstellungen des Hue Geräte (CCU) gibt es zwei Werte:
RGBW_COLOR|DEFAULT_SATURATION und RGBW_COLOR\|WHITE_HUE_VALUE
Damit kann der Wert eingestellt werden, der verwendet wird, wenn die CCU weiß als Farbe sendet (WHITE_HUE_VALUE) bzw wie der Saturation Wert sein soll, den die Lampe bekommt wenn allgemein Farben gesendet werden.


Hochdimmen per Taster geht nicht, da die CCU keinen LONG_PRESS_CONTINUE Wert sendet. Also ich bekomme nicht gesagt, wenn der User die Taste festhält, sondern nur er hat sie lange gedrückt.

**Comment by DerChecker** [comment]
Vielen Dank für die schnelle Rückmeldung. Schade dass man die Taste nicht retriggern lassen kann.
Ich werde es mal ausprobieren mit den Werteeinstellungen. So ganz scheine ich das Ganze jedoch noch nicht zu durchblicken. Mit meinem Neo Automation Server konnte ich mit mehrfachem langen Tastendruck hintereinander die Lampen hoch und runterdimmen. Könnte man das implementieren? Ansonsten klappt das alles schon echt gut.

**Comment by thkl** [comment]
Ab dem nächsten Version des LogicPlugins wird so ein Verhalten mit einem 2 Zeilen Script möglich sein. 

Ich muss da nur noch bissel aufräumen.

**Comment by DerChecker** [comment]
Warum denn geschlossen. Wird nicht mehr weiter entwickelt?

**Comment by thkl** [comment]
Es gibt im Logic Plugin eine LinkLightSwitch Funktion die genau das mit einer Zeile ScriptCode macht.  https://github.com/thkl/Homematic-Virtual-Interface/wiki/linkLightSwitch

**Comment by DerChecker** [comment]
Alles klar, vielen Dank!

Am 19. Januar 2020 21:22:29 MEZ schrieb Thomas Kluge <notifications@github.com>:
>Es gibt im Logic Plugin eine LinkLightSwitch Funktion die genau das mit
>einer Zeile ScriptCode macht. 
>https://github.com/thkl/Homematic-Virtual-Interface/wiki/linkLightSwitch
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/thkl/Homematic-Virtual-Interface/issues/31#issuecomment-576042881

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
