### ISSUE TITLE
Uninstall removes InterfacesList.xml

### ISSUE THREAD

**Issue by leonsio** [thkl/Homematic-Virtual-Interface#35]
Hi Thomas

habe dein Skript zugegebenermaßen nicht getestet, aber wenn ich mir die Datei rc.d/ccu_hvl ansehe, finde ich bei uninstall ein rm -rf auf die InterfacesList Datei was sicherlich nicht gewollt ist?

```shell

   uninstall)
        logger -t homematic -p user.info "removing homematic virtual layer"
        rm -r /usr/local/etc/config/addons/www/hvl
        rm -r /usr/local/etc/config/rc.d/ccu_hvl
        rm -f /etc/config/InterfacesList.xml
        rm -f /etc/init.d/S59hvl
        ;;

```

Gruß

Leo

**Comment by thkl** [comment]
Naja beim Reboot der CCU wird diese ja wieder aus config/templates erstellt ....

**Comment by leonsio** [comment]
also machst du dir die Arbeit leichter ;) kann aber eventuell zu Problemen führen wenn einige Module beim Start nicht prüfen ob die Interfaces Einträge richtig sind, bzw. ob die Einträge auch in dem Template vorhanden sind

**Comment by Larson-Sei180LX** [comment]
Bei mir führte glaub genau das zu problemen. Wired wird nicht mehr erkannt, seit dem letzten Update von HVL
