### ISSUE TITLE
Link zum Rasperry CCU Addin funktioniert nicht

### ISSUE THREAD

**Issue by TobiasSt78** [thkl/Homematic-Virtual-Interface#36]
Wo kann ich das Plugin für die Rasperrymatic finden?

**Comment by thkl** [comment]
aktuelle version https://github.com/thkl/Homematic-Virtual-Interface/blob/master/raspberrymatic_installer/ und dort das 

hvl-raspb-.....tar.gz in der jeweiligen Version
