### ISSUE TITLE
Raspberrymatic Addon Installation nicht möglich

### ISSUE THREAD

**Issue by frawie** [thkl/Homematic-Virtual-Interface#38]
Hallo,
versuche bei Raspberrymatic Addon Homematic-Virtual-Interface "hvl-raspb-0.0.7.tar" zu installieren.
Habe es mehrmals probiert auch mit Pause von 30 Minuten ohne Erfolg.
Immer wenn ich versuche darauf zu zugreifen kommt die Meldung Seite ist nicht vorhanden "http://192.168.5.101:8300/". Habe zu diesen Thema nichts gefunden, mehrmals installiert und deinstalliert. Raspberrymatic neu aufgesetzt, alles ohne Erfolg.

In den Logfiles vom npm-debug.log ist folgendes sichtbar:
 http request GET https://registry.npmjs.org/homematic-virtual-interface
 info retry will retry, error on last attempt: Error: connect ENETUNREACH 151.101.112.162:443 - Local (0.0.0.0:0)
info attempt registry request try #2 at 3:27:32 PM
 http request GET https://registry.npmjs.org/homematic-virtual-interface
info retry will retry, error on last attempt: Error: connect ENETUNREACH 151.101.112.162:443 - Local (0.0.0.0:0)
 info attempt registry request try #3 at 3:28:32 PM
 http request GET https://registry.npmjs.org/homematic-virtual-interface
silly fetchPackageMetaData Error: connect ENETUNREACH 151.101.112.162:443 - Local (0.0.0.0:0)
 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1022:11)
 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1045:20)
 silly fetchPackageMetaData     at connect (net.js:881:16)
silly fetchPackageMetaData     at net.js:1010:7
25 silly fetchPackageMetaData     at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
25 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)
25 silly fetchPackageMetaData  error for homematic-virtual-interface { Error: connect ENETUNREACH 151.101.112.162:443 - Local (0.0.0.0:0)
 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1022:11)
 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1045:20)
 silly fetchPackageMetaData     at connect (net.js:881:16)
 silly fetchPackageMetaData     at net.js:1010:7
silly fetchPackageMetaData     at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)
silly fetchPackageMetaData   code: 'ENETUNREACH',
 silly fetchPackageMetaData   errno: 'ENETUNREACH',
 silly fetchPackageMetaData   syscall: 'connect',
 silly fetchPackageMetaData   address: '151.101.112.162',
 silly fetchPackageMetaData   port: 443 }
silly rollbackFailedOptional Starting
silly rollbackFailedOptional Finishing
silly runTopLevelLifecycles Finishing
 silly install printInstalled
 verbose stack Error: connect ENETUNREACH 151.101.112.162:443 - Local (0.0.0.0:0)
 verbose stack     at Object.exports._errnoException (util.js:1022:11)
 verbose stack     at exports._exceptionWithHostPort (util.js:1045:20)
 verbose stack     at connect (net.js:881:16)
 verbose stack     at net.js:1010:7

Zur Info ich habe Internetanschluss Kabel Deutschland DualStack-Lite. Kann es hier Probleme mit IPv4 gibt.

Danke für die Hilfe

**Comment by thkl** [comment]
Schaut so aus, als ob das Addon nicht die notwendigen Files laden kann.  Kann das sein, das die CCU nicht auf das Inet zugreifen darf ?

**Comment by frawie** [comment]
Danke für die schnelle Antwort.
Raspberrymatic kann auf das Internet zugreifen. Emails senden geht jedenfalls.
Kann es Problem mit meinen Kabel Anschluss und IPv6 geben ?

**Comment by frawie** [comment]
Gibt es die Möglichkeit fehlende Dateien händisch zu installieren (auf Raspberrymatic).

**Comment by thkl** [comment]
Händisch ? Also scheinbar wurde ja node schon geladen und installiert.  Die Frage ist jetzt warum die rm keinen Zugang zur node registry hat.  Ggf einfach noch mal probieren.

**Comment by frawie** [comment]
Ich habe es mehrmals ausprobiert ohne Erfolg. Bin nicht der große Experte mit Linux, aber gibt es die Möglichkeit die daten Manuell zu installieren und wenn ja wie muss man es machen?
Bekomme auch die Meldung "Eine Komponente der HomeMatic Zentrale reagiert nicht mehr." und verweist auf HVL.

**Comment by thkl** [comment]
Manuell macht keinen Sinn denn es sind zu viele Abhängigkeiten die installiert werden. Und jedes Plugin installiert auch noch mal Module.

**Comment by frawie** [comment]
Hatte jetzt erst wieder Zeit gehabt es an einem anderen DSL Anschluss auszuprobieren. Jetzt konnte ich es laden und installieren.
Danke für die Unterstützung
