### ISSUE TITLE
Fehler beim ersetzen von xmlrpc in homematic-virtual-interface/lib/HomematicLogicLayer.js

### ISSUE THREAD

**Issue by coolsurfer** [thkl/Homematic-Virtual-Interface#4]
1. in **homematic-virtual-interface/lib/HomematicLogicLayer.js** in Zeile 47 wird xmlrpc pauschal durch http ersetzt. Wenn ich die Schnittstelle initalisiere (nicht von der CCU2 aus, sondern aus einem eigenen Programm) kommt es zu folgendem Fehler:

Mein INIT Befehl für Port 7000 benutzt ein Script names **xmlrpcServer.php**. **http://123.456.789.012:80/xmlrpcServer.php**, was ersetzt wird durch http://123.456.789.012:80/httpServer.php

2. Zudem schlägt ein INIT ohne Portangabe fehl (dabei ist die Portangabe normalerweise eher optional)

3. ein INIT an Port 7000 funktioniert zwar, resultiert aber in einem TimeOut, weil keine XMLRPC-konforme Antwort kommt.

**Comment by thkl** [comment]
ja, aber das Problem ist, das die CCU xmlrpc://.... als Init auf die Schnittstelle sendet. Ich muss aber als http.// antworten.  Ok das ist dreckig, but works for me ;o)

**Comment by thkl** [comment]
ok sollte in https://github.com/thkl/Homematic-Virtual-Interface/commit/f59d1b39448d7b26cb3d17eada24ff73e8eb1f5c erledigt sein

**Comment by coolsurfer** [comment]
Das mit dem "protocol" geht so evtl. ich würde ein startsWith() machen und wenn das true ist, dann das entsprechende replace. Weil replace ersetzt ja nur das erste Vorkommen, was ja dann das erste xmlrpc... ist, was ganz am anfang steht, sonst wäre startWith ja false.

Oder ein replace auf "xmlrpc://" und "xmlrpc_bin://". Aber deine Lösung scheint auch ganz praktikabel, baut aber evtl. neue Probleme ein...

Alles andere kann lokal bei mir erst morgen testen; danke für die schnelle Fixes...

**Comment by coolsurfer** [comment]
Danke. Scheint soweit einwandfrei zu funktionieren. Was mir jedoch aufgefallen ist: Wenn ich ein INIT (leer) sende, dann schreibt das LOG zwar "[HomematicLogicalLayer] [INFO] - there is a removal" aber auf der Startseite bleiben "3 active Connections"; sprich dort wird der entsprechende Eintrag nicht gelöscht, ob auch tatsächlich noch regelmäßig Updates an das entfernte Script erfolgen, hab ich auf die Schnelle jetzt nicht geprüft.

**Comment by thkl** [comment]
Hmm ich muss mal schauen was ich da tue :) das ist schon lange her das ich das gebaut habe

**Comment by coolsurfer** [comment]
Hier ist ein Patch dafür:

`@@ -486,6 +486,7 @@ HomematicLogicalLayer.prototype.init = function()
 					callback(null,[]);
 				}
  			} else {
+ 				cns.initwithurl(that.ccuIP,params[0],params[1]);
  				that.removeOldConsumer(cns);
  				that.saveConsumer();
 				logger.info("there is a removal");
@@ -683,7 +684,7 @@ HomematicLogicalLayer.prototype.isHMServer = funct
 HomematicLogicalLayer.prototype.addConsumer = function(aConsumer) {
   // TODO Check if we have to purge old Consumers
   logger.debug("Adding new Consumer");
-  this.consumer = this.removeOldConsumer(aConsumer);
+  this.removeOldConsumer(aConsumer);
   this.consumer.push(aConsumer);
 }
 
@@ -715,8 +716,8 @@ HomematicLogicalLayer.prototype.cleanUp = function
 }
 
 HomematicLogicalLayer.prototype.removeOldConsumer = function(newconsumer) {
-  var result =  this.consumer.filter(function(ctt) { return !ctt.isEqual(newconsumer); });
-  return result;
+  var result = this.consumer.filter(function(ctt) { return !ctt.isEqual(newconsumer); });
+  this.consumer = result;
 }
 `

**Comment by JensBonse** [comment]
Hi! Seit dem Update auf 0.2.40 habe ich nun 2 Aktive Verbindungen. Die Erste ist ganz normal zur CCU die zweite zeigt folgendes:  null:80xmlrpc_bin://127.0.0.1:1999

**Comment by thkl** [comment]
@Jens ich glaub den kannst du nur aus der persist.json manuell löschen

**Comment by jens** [comment]
Sorry, wrong Jens. :-)

**Comment by thkl** [comment]
Oops 🙊

**Comment by JensBonse** [comment]
So, habe es aus der persist.json gelöscht und den Dienst restarted. Sieht wieder sauber aus.
@jens You mean different Jens. I am a real Jens ;)

**Comment by thkl** [comment]
kann zu oder ?
