### ISSUE TITLE
Amazon Dash-Button unter Raspberrymatic

### ISSUE THREAD

**Issue by capitaenz** [thkl/Homematic-Virtual-Interface#43]
Hallo Thomas,

ich möchte vorsichtig fragen, ob es Hoffnung für das Dash-Button Plug in unter Raspberrymatic gibt.
Eine Einbindung mit CUxD scheitert, da die Ping-Abfrage mit 15 Sec. leider zu grob ist.

VG
Leif

**Comment by coolsurfer** [comment]
Nimm einfach einen AWS IoT Button (https://www.amazon.com/dp/B01KW6YCIM), dann legst du ein kleines Script (lokal) an, welches durch den Button (ggf. per Lambda Proxy) aufgerufen wird. Mit dem Script erzeugst du einen MQTT-Eintrag den du dann z.B. mit dem MQTT-SONOFF Interface wieder auswertest.
