### ISSUE TITLE
link for Raspberry-Matic not avaliable

### ISSUE THREAD

**Issue by vdemden** [thkl/Homematic-Virtual-Interface#44]
Page / Projekt linked  in md file for Raspberry Matic not avaliable...

**Comment by thkl** [comment]
?

**Comment by comtel2000** [comment]
I guess @vdemden refers to the deprecated link in the README.md ...If you want to use this on an Raspberrymatic CCU , please use this **CCU Addon.** ...

**Comment by MathiasH82** [comment]
https://github.com/thkl/Homematic-Virtual-Interface/raw/master/raspberrymatic_installer/hvl-raspb-0.0.7.tar.gz
