### ISSUE TITLE
Lässt sich auf separaten Pi nicht installieren

### ISSUE THREAD

**Issue by Raimundschmidt** [thkl/Homematic-Virtual-Interface#45]
Ich habe HVL bereits installiert gehabt und alles hat wunderbar funktioniert.
Da ich etwas Zeit übrig hatte und mein Pi 3 überfordert war habe ich alles neu aufgesetzt. Nachdem ich über SSH den Installationslink Aufrufe tut sich schnell was und er fragt mich auch ob ich HVL beim booten automatisch starten möchte, allerdings kommen paar Meldungen bzgl fehlenden Verzeichnisse und HVL lässt sich über die IP nicht aufrufen. Was mach ich falsch? Kann mir jemand weiterhelfen? Wenn noch Infos benötigt werden kann ich diese gerne nachreichen. 
![20180425_082041](https://user-images.githubusercontent.com/38714945/39229097-9336e418-4861-11e8-8217-3662ec6d818d.jpg)

**Comment by Muecke85** [comment]
Hi, probiere mal:

/home/pi/node_modules/homematic-virtual-interface/bin/hmviservice start

**Comment by Raimundschmidt** [comment]
Hallo, 

das werde ich mal am Wochenende probieren und dann berichten.

Vielen Dank schon mal!
