### ISSUE TITLE
Ikea Tradfri Verbindung wird abgelehnt

### ISSUE THREAD

**Issue by WilhelmFaber** [thkl/Homematic-Virtual-Interface#46]
Ikea Tradfri Plugin kann sich nicht verbinden. 

Raspberrymatic: 2.31.25.20180428

HVI wurde in der Version hvl-raspb-0.0.7.tar.gz installiert.

Unter Settings IkeaTradfri wurde die richtige Security ID und Bridge ID eingetragen dennoch kommt keine Verbindung zur Stande.

Logeinträge:

Tue May 01 2018 20:42:41 GMT+0200 (CEST)[homematic-virtual-tradfridevice - IkeaTradfri] [WARN] - we have to authenticate first
Tue May 01 2018 20:42:40 GMT+0200 (CEST)[homematic-virtual-tradfridevice - IkeaTradfri] [WARN] - we have to authenticate first
Tue May 01 2018 20:42:38 GMT+0200 (CEST)[homematic-virtual-tradfridevice - IkeaTradfri] [WARN] - we have to authenticate first
Tue May 01 2018 20:42:36 GMT+0200 (CEST)[homematic-virtual-tradfridevice - IkeaTradfri] [WARN] - we have to authenticate first

**Comment by Raimundschmidt** [comment]
Hi,

ich konnte mich von Beginn an nicht verbinden bzw. ich bekam die selbe Meldung wie WilhelmFaber schon im Logeintrag gezeigt hatte. Aktuell habe ich dazu auch keine Lösung und wundere mich ein bisschen, dass es bei den anderen einwandfrei funktioniert. Vielleicht hat jemand einen Tipp, was wir falsch machen.

Vielen Dank und liebe Grüße
Raimund

**Comment by WilhelmFaber** [comment]
Hallo, vielleicht kennt Jemand das Problem und kann hier die Hilfestellung leisten? Das wäre echt super. Gruß

**Comment by fastcrash** [comment]
Hi,

in der Doku zu node-tradfri-client, das ja für die Verbindung zuständig ist, ist die Rede davon, dass es je nach Netzwerk Probleme mit der Nutzung der IP gibt. Alternativ kann ja auch der Hostname genutzt werden. Ich kann es gerade leider nicht testen, aber vielleicht liegt es ja daran.

Gruß
Robert

**Comment by Marco4223** [comment]
Läuft leider bei mir auch mit der Änderung nicht. Sobald ich die Config geändert und gespeichert habe hat sich diese wieder in die alte Form gewandelt. (Wird wohl kontinuierlich geschrieben) Ein Fix hierfür wäre schön. :)

**Comment by Marco4223** [comment]
Konnte schon jemand dieses Problem beheben? (Die Methode die hier aufgeführt wird funktioniert bei mir nicht)
Tue Sep 11 2018 16:09:26 GMT+0200 (CEST)[homematic-virtual-tradfridevice - IkeaTradfri] [WARN] - we have to authenticate first
Tue Sep 11 2018 16:09:24 GMT+0200 (CEST)[homematic-virtual-tradfridevice - IkeaTradfri] [WARN] - we have to authenticate first
Tue Sep 11 2018 16:09:23 GMT+0200 (CEST)[homematic-virtual-tradfridevice - IkeaTradfri] [WARN] - we have to authenticate first
Tue Sep 11 2018 16:09:22 GMT+0200 (CEST)[homematic-virtual-tradfridevice - IkeaTradfri] [WARN] - we have to authenticate first
Tue Sep 11 2018 16:09:21 GMT+0200 (CEST)[homematic-virtual-tradfridevice - IkeaTradfri] [WARN] - we have to authenticate first
Tue Sep 11 2018 16:09:20 GMT+0200 (CEST)[homematic-virtual-tradfridevice - IkeaTradfri] [WARN] - we have to authenticate first
Tue Sep 11 2018 16:09:19 GMT+0200 (CEST)[homematic-virtual-tradfridevice - IkeaTradfri] [WARN] - we have to authenticate first
Tue Sep 11 2018 16:09:17 GMT+0200 (CEST)[homematic-virtual-tradfridevice - IkeaTradfri] [WARN] - we have to authenticate first
Tue Sep 11 2018 16:09:16 GMT+0200 (CEST)[homematic-virtual-tradfridevice - IkeaTradfri] [WARN] - we have to authenticate first
Tue Sep 11 2018 16:09:15 GMT+0200 (CEST)[homematic-virtual-tradfridevice - IkeaTradfri] [WARN] - we have to authenticate first
Tue Sep 11 2018 16:09:14 GMT+0200 (CEST)[homematic-virtual-tradfridevice - IkeaTradfri] [WARN] - we have to authenticate first
Tue Sep 11 2018 16:09:13 GMT+0200 (CEST)[homematic-virtual-tradfridevice - IkeaTradfri] [WARN] - we have to authenticate first
Tue Sep 11 2018 16:09:11 GMT+0200 (CEST)[homematic-virtual-tradfridevice - IkeaTradfri] [WARN] - we have to authenticate first
Tue Sep 11 2018 16:09:10 GMT+0200 (CEST)[homematic-virtual-tradfridevice - IkeaTradfri] [WARN] - we have to authenticate first
Tue Sep 11 2018 16:09:09 GMT+0200 (CEST)[homematic-virtual-tradfridevice - IkeaTradfri] [WARN] - we have to authenticate first
Tue Sep 11 2018 16:09:08 GMT+0200 (CEST)[homematic-virtual-tradfridevice - IkeaTradfri] [WARN] - we have to authenticate first
Tue Sep 11 2018 16:09:06 GMT+0200 (CEST)[homematic-virtual-tradfridevice - IkeaTradfri] [WARN] - we have to authenticate first
Tue Sep 11 2018 16:09:05 GMT+0200 (CEST)[homematic-virtual-tradfridevice - IkeaTradfri] [WARN] - we have to authenticate first
Tue Sep 11 2018 16:09:03 GMT+0200 (CEST)[homematic-virtual-tradfridevice - IkeaTradfri] [WARN] - we have to authenticate first
Tue Sep 11 2018 16:09:03 GMT+0200 (CEST)[homematic-virtual-tradfridevice - IkeaTradfri] [ERROR] - Gateway authentication error SyntaxError: Unexpected end of JSON input

**Comment by thkl** [comment]
Die Authentifizierung basiert nicht auf dem auf dem Gateway aufgedruckten Security Code sondern aus einem daraus abgeleiteten User/PSK. 
Der Security Code darf auf Bitten von Ikea nirgendwo gespeichert werden. 

Wenn das Plugin über die Weboberfläche eingerichtet wird, dann muss in dessen Config der Security Code und die IP eingetragen werden. 

Daraus ermittelt das Gateway dann den User und den PSK und speichert den in der Config. 

Die Meldung we have to authenticate first kommt daher, das das Gateway den übergeben User und PSK ablehnt.  Einfach mal das aus der Config werfen und den Gateway Code noch mal auf der Webseite des Plugins eintragen.

**Comment by Marco4223** [comment]
Hallo thkl,
sorry für die späte Antwort.
Habe jetzt die Informationen aus der /usr/local/etc/config/hvl/config.json gelöscht und das Plugin über die UI neu konfiguriert. 
Leider ohne Erfolg. Ich bekomme immer noch die gleiche Meldung. 
Nur um Sicher zu gehen: Die Sec ID ist ca. 16 stellen lang und mehr nicht, richtig? 
VG
Marco

**Comment by Marco4223** [comment]
Plugin deinstalliert, rebootet, deinstalliert und dann Sec Code und IP neu eingetragen und was soll man sagen? Geht nicht.
Was mich auch stutzig mach ist das dieses Plugin anscheinend weiterhin aktiv ist da es, trotz das ich es auf deaktiviert habe, alle paar Sekunden den identity und psk in der Konfig neu schreibt.  
Wenn ich dein Aussage richtig interpretiere dann sind die beiden werte aus IP und SEC Code abgeleitet. Wie kann man den aus zwei statischen werten alle paar Sekunden was neues ableiten?
Zusätzlich noch ein..zwei Auffälligkeiten.
Einmal deaktiviert kann ich das plugin nicht mehr aktivieren. Ich muss das ganze HVL neu installieren, dann klappt es.
Zudem geht die Meldung
Version > 0.0.17 Requires NodeJS >= 6.x
nicht weg obwohl ich 6.10 drauf habe:
# node -v
v6.10.0

**Comment by Marco4223** [comment]
Ach ja, ein Nebeneffekt bei dem ganzen versuchen der Anmeldung ist, das sich das Gateway schlussendlich aus dem Netzwerk verabschiedet und somit nicht mehr nutzbar ist.

**Comment by MamaLilla** [comment]
Hallo,
ich habe leider auch das beschriebene Problem. Hat mittlerweile jemand eine Lösung?

Ich habe es frisch installiert und nur über die Weboberfläche konfiguriert. Zu beginn kam noch 1-2x "wrong password" mittlerweile nur noch "we have to authenticate first"
