### ISSUE TITLE
HVL Button entfernen

### ISSUE THREAD

**Issue by weaverprojects** [thkl/Homematic-Virtual-Interface#47]
Wie kann ich nach einer Deinstallation in der Systemsteuerung den HVL Button entfernen?
![bildschirmfoto 2018-07-24 um 16 48 58](https://user-images.githubusercontent.com/26321173/43146531-b130323e-8f61-11e8-8337-cd9030639baa.png)

**Comment by DerChecker** [comment]
Würde mich auch interessieren.

**Comment by thkl** [comment]
das macht inzwischen das Plugin

die Addon Buttons sind auf der CCU in der Datei /etc/config/hm_addons.cfg konfiguriert

**Comment by DerChecker** [comment]
Danke für die schnelle Antwort. Ich bekomme es leider trotzdem nicht hin. Wo muss ich klicken, damit sich das Plugin vollständig entfernt?

 

Von: Thomas Kluge [mailto:notifications@github.com] 
Gesendet: Mittwoch, 22. Januar 2020 18:42
An: thkl/Homematic-Virtual-Interface <Homematic-Virtual-Interface@noreply.github.com>
Cc: DerChecker <edst@freenet.de>; Comment <comment@noreply.github.com>
Betreff: Re: [thkl/Homematic-Virtual-Interface] HVL Button entfernen (#47)

 

das macht inzwischen das Plugin

die Addon Buttons sind auf der CCU in der Datei /etc/config/hm_addons.cfg konfiguriert
