### ISSUE TITLE
putParamset verändert zwar das paramset aber nicht die Eigenschaft selbst

### ISSUE THREAD

**Issue by coolsurfer** [thkl/Homematic-Virtual-Interface#5]
Wenn ich ein XMLRPC mit putParamset an den Port 7000 sende (Anhang), dann wird zwar das Paramset korrekt mit LEVEL 1 zurückgeliefert (zumindest solange bis wieder ein Update der Hue angefordert wird), die Hue Lampe z. B. bleibt aber aus, wenn Sie aus war. Der XMLRPC-Aufruf mit "setValue" funktioniert hingegen einwandfrei (verändert das Paramset und steuert die Hue Lampe).

**Comment by coolsurfer** [comment]
[putParamset.xml.txt](https://github.com/thkl/Homematic-Virtual-Interface/files/944785/putParamset.xml.txt)

**Comment by thkl** [comment]
gefixt mit Core 0.2.44
