### ISSUE TITLE
IKEA Tradfri: No possibility switch on/off lamp programmatically

### ISSUE THREAD

**Issue by cRemE-fReSh** [thkl/Homematic-Virtual-Interface#50]
Hi,
I'm testing HVI together with the Tradfri Addon.

I'm able to control the connected lamps using the Homematic UI. But I can't create a program that switches the lamp on or off. Find below a screenshot showing the available actions. The action to switch on or off is missing.

![2018-08-28 22_19_48-homematic webui](https://user-images.githubusercontent.com/42785404/44748640-868cc900-ab10-11e8-88de-5e2fb2f1dd2d.png)

Is there any chance to do so? Without this functionality the plugin seems to me worthless for me.

Kind regards

**Comment by thkl** [comment]
Please try „Dimmwert“ to switch the lights  on and off

**Comment by cRemE-fReSh** [comment]
I've tried that before but this time it works now.

**Comment by cRemE-fReSh** [comment]
I want to add one remark. It does not work if I set the "Dimmwert" to 85% but e.g. for 84%. That is why it has not worked before. It also works with 100% but not with 85.

**Comment by thkl** [comment]
Ok, that sounds strange.  I will take a look into it.

**Comment by thkl** [comment]
After a few tests i can not confirm this. 85% are working, but there is a smaller issue: the plugin will report 86% back to the ccu ... i am currently not sure why  ..

**Comment by thkl** [comment]
Ok bitte mal in den Debug Modus wechseln.
Das geht unter ServiceMode/Log Anzeigen .. da gibts links ein Debug einschalten.
Dadurch bootet HVL einmal und das Log wird sehr sehr groß ;)

Dann einmal das Programm mit den 85% starten und im HVL unter ServiceMode/Log Anzeigen nachschauen, ob das angekommen ist.

Das schaut ungefähr so aus und ist von unten nach oben zu lesen:

```
Wed Aug 29 2018 19:40:10 GMT+0200 (CEST)[HomematicLogicalLayer] [DEBUG] - RPC Out -> method:event | params:["3424","Tradfri65537:1","LEVEL",{"explicitDouble":0.86}]
Wed Aug 29 2018 19:40:10 GMT+0200 (CEST)[HomematicLogicalLayer] [DEBUG] - Device Value Change Event for Tradfri65537:1
Wed Aug 29 2018 19:40:10 GMT+0200 (CEST)[HomematicChannel] [DEBUG] - Channel update Event
Wed Aug 29 2018 19:40:10 GMT+0200 (CEST)[homematic-virtual-tradfridevice - IkeaTradfri] [DEBUG] - update Lamp 65537
Wed Aug 29 2018 19:40:10 GMT+0200 (CEST)[HomematicDevice] [DEBUG] - Channel Value event LEVEL
Wed Aug 29 2018 19:40:10 GMT+0200 (CEST)[HomematicChannel] [DEBUG] - Parameter value change event LEVEL
Wed Aug 29 2018 19:40:10 GMT+0200 (CEST)[HomematicChannel] [DEBUG] - Channel set Value LEVEL to 0.85
```

unterste Zeile ist der Event der ankommt wenn das Programm den Datenpunkt setzt.
Dann wird in der Mitte die Lampe upgedatet.
Und gleichzeitig wird der Wert wieder von der Lampe gelesen und als 0,86 an die CCU gesendet.

**Comment by cRemE-fReSh** [comment]
Mache ich. Aber ich werde das erst am Sonntag machen können. Bin unterwegs.

**Comment by cRemE-fReSh** [comment]
Also, ich habe gerade einen Log erstellt.
-  Programm auf 85% geändert. Licht geht nicht mehr an.
- Debug aktiviert. Licht geht auf einmal an.
`Sun Sep 02 2018 21:25:41 GMT+0200 (CEST)[Homematic Virtual Interface.Server] [DEBUG] - Server HTTP Request /index/?showlog parsed /index/ {"showlog":""}
Sun Sep 02 2018 21:25:41 GMT+0200 (CEST)[Homematic Virtual Interface.Server] [DEBUG] - index is mine
Sun Sep 02 2018 21:25:41 GMT+0200 (CEST)[Homematic Virtual Interface.Server] [DEBUG] - request index not handled by a plugin try mine
Sun Sep 02 2018 21:25:27 GMT+0200 (CEST)[HomematicLogicalLayer] [DEBUG] - repl  > ["system.listMethods","listDevices","getDeviceDescription","getLinks","getValue","setValue","getParamsetDescription","getParamsetId","getParamset","reportValueUsage","deleteDevice","getLinkPeers","system.methodHelp","putParamset","init","ping"]
Sun Sep 02 2018 21:25:27 GMT+0200 (CEST)[HomematicLogicalLayer] [DEBUG] - rpc < system.listMethods ()
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[HomematicChannel] [DEBUG] - Ignore Value Change Tradfri65539:1.WHITE event because the value doesnt change 4500 vs 4500
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[HomematicChannel] [DEBUG] - Channel update Event
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[HomematicChannel] [DEBUG] - Ignore Value Change Tradfri65539:1.LEVEL event because the value doesnt change 0.85 vs 0.85
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[homematic-virtual-tradfridevice - IkeaTradfri] [DEBUG] - Update Color for White Lamp f1e0b5
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[HomematicChannel] [DEBUG] - Channel update Event
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[homematic-virtual-tradfridevice - IkeaTradfri] [DEBUG] - Update Level for  Lamp 85
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[HomematicChannel] [DEBUG] - Ignore Value Change Tradfri65539:1.WHITE event because the value doesnt change 4500 vs 4500
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[HomematicChannel] [DEBUG] - Channel update Event
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[homematic-virtual-tradfridevice - IkeaTradfri] [DEBUG] - Update Color for White Lamp f1e0b5
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[HomematicLogicalLayer] [DEBUG] - RPC Out -> method:event | params:["14581","Tradfri65539:1","LEVEL",{"explicitDouble":0.85}]
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[HomematicLogicalLayer] [DEBUG] - RPC Out -> method:event | params:["HVL_java","Tradfri65539:1","LEVEL",{"explicitDouble":0.85}]
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[HomematicLogicalLayer] [DEBUG] - Device Value Change Event for Tradfri65539:1
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[HomematicChannel] [DEBUG] - Channel update Event
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[homematic-virtual-tradfridevice - IkeaTradfri] [DEBUG] - Update Level for  Lamp 85
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[HomematicChannel] [DEBUG] - Ignore Value Change Tradfri65539:1.WHITE event because the value doesnt change 4500 vs 4500
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[HomematicChannel] [DEBUG] - Channel update Event
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[homematic-virtual-tradfridevice - IkeaTradfri] [DEBUG] - Update Color for White Lamp f1e0b5
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[HomematicLogicalLayer] [DEBUG] - RPC Out -> method:event | params:["14581","Tradfri65539:1","LEVEL",{"explicitDouble":0}]
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[HomematicLogicalLayer] [DEBUG] - RPC Out -> method:event | params:["HVL_java","Tradfri65539:1","LEVEL",{"explicitDouble":0}]
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[HomematicLogicalLayer] [DEBUG] - Device Value Change Event for Tradfri65539:1
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[HomematicChannel] [DEBUG] - Channel update Event
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[homematic-virtual-tradfridevice - IkeaTradfri] [DEBUG] - Update Level for  Lamp 85
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[HomematicLogicalLayer] [DEBUG] - RPC Out -> method:event | params:["14581","Tradfri65539:1","LEVEL",{"explicitDouble":0.85}]
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[HomematicLogicalLayer] [DEBUG] - RPC Out -> method:event | params:["14581","Tradfri65539:1","WORKING",false]
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[HomematicLogicalLayer] [DEBUG] - RPC Out -> method:event | params:["HVL_java","Tradfri65539:1","LEVEL",{"explicitDouble":0.85}]
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[HomematicLogicalLayer] [DEBUG] - RPC Out -> method:event | params:["HVL_java","Tradfri65539:1","WORKING",false]
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[HomematicLogicalLayer] [DEBUG] - Device Value Change Event for Tradfri65539:1
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[HomematicDevice] [DEBUG] - Channel Value event WORKING
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[HomematicChannel] [DEBUG] - Parameter value change event WORKING
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[HomematicChannel] [DEBUG] - Ignore Value Change Tradfri65539:1.LEVEL event because the value doesnt change 0.85 vs 0.85
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[HomematicChannel] [DEBUG] - Channel set Value WORKING to false
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[HomematicChannel] [DEBUG] - Channel update Event
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[HomematicLogicalLayer] [DEBUG] - RPC Out -> method:event | params:["14581","Tradfri65539:1","LEVEL",{"explicitDouble":0.85}]
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[HomematicLogicalLayer] [DEBUG] - RPC Out -> method:event | params:["14581","Tradfri65539:1","WORKING",true]
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[HomematicLogicalLayer] [DEBUG] - RPC Out -> method:event | params:["HVL_java","Tradfri65539:1","LEVEL",{"explicitDouble":0.85}]
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[HomematicLogicalLayer] [DEBUG] - RPC Out -> method:event | params:["HVL_java","Tradfri65539:1","WORKING",true]
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[HomematicDevice] [DEBUG] - Channel Value event WORKING
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[HomematicLogicalLayer] [DEBUG] - Device Value Change Event for Tradfri65539:1
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[HomematicChannel] [DEBUG] - Parameter value change event WORKING
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[HomematicChannel] [DEBUG] - Channel set Value WORKING to true
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[HomematicDevice] [DEBUG] - Channel Value event LEVEL
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[HomematicChannel] [DEBUG] - Parameter value change event LEVEL
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[HomematicChannel] [DEBUG] - Channel set Value LEVEL to 0.85
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[HomematicLogicalLayer] [DEBUG] - repl  >  
Sun Sep 02 2018 21:25:19 GMT+0200 (CEST)[HomematicLogicalLayer] [DEBUG] - rpc < setValue Tradfri65539:1,LEVEL,0.85`
- Debug wieder deaktiviert. Licht geht nicht mehr an. Wert wieder auf 84% geändert.

- Debug bei eingeschaltetem Licht (84%) wieder aktiviert. Licht geht nicht mehr aus.
`Sun Sep 02 2018 21:31:45 GMT+0200 (CEST)[HomematicLogicalLayer] [DEBUG] - RPC Out -> method:event | params:["14581","Tradfri65539:1","LEVEL",{"explicitDouble":0}]
Sun Sep 02 2018 21:31:45 GMT+0200 (CEST)[HomematicLogicalLayer] [DEBUG] - RPC Out -> method:event | params:["14581","Tradfri65539:1","WORKING",false]
Sun Sep 02 2018 21:31:45 GMT+0200 (CEST)[HomematicLogicalLayer] [DEBUG] - RPC Out -> method:event | params:["HVL_java","Tradfri65539:1","LEVEL",{"explicitDouble":0}]
Sun Sep 02 2018 21:31:45 GMT+0200 (CEST)[HomematicLogicalLayer] [DEBUG] - RPC Out -> method:event | params:["HVL_java","Tradfri65539:1","WORKING",false]
Sun Sep 02 2018 21:31:45 GMT+0200 (CEST)[HomematicLogicalLayer] [DEBUG] - Device Value Change Event for Tradfri65539:1
Sun Sep 02 2018 21:31:45 GMT+0200 (CEST)[HomematicDevice] [DEBUG] - Channel Value event WORKING
Sun Sep 02 2018 21:31:45 GMT+0200 (CEST)[HomematicChannel] [DEBUG] - Parameter value change event WORKING
Sun Sep 02 2018 21:31:45 GMT+0200 (CEST)[HomematicChannel] [DEBUG] - Channel set Value WORKING to false
Sun Sep 02 2018 21:31:45 GMT+0200 (CEST)[HomematicChannel] [DEBUG] - Channel update Event
Sun Sep 02 2018 21:31:45 GMT+0200 (CEST)[HomematicLogicalLayer] [DEBUG] - RPC Out -> method:event | params:["14581","Tradfri65539:1","LEVEL",{"explicitDouble":0}]
Sun Sep 02 2018 21:31:45 GMT+0200 (CEST)[HomematicLogicalLayer] [DEBUG] - RPC Out -> method:event | params:["14581","Tradfri65539:1","WORKING",true]
Sun Sep 02 2018 21:31:45 GMT+0200 (CEST)[HomematicLogicalLayer] [DEBUG] - RPC Out -> method:event | params:["HVL_java","Tradfri65539:1","LEVEL",{"explicitDouble":0}]
Sun Sep 02 2018 21:31:45 GMT+0200 (CEST)[HomematicLogicalLayer] [DEBUG] - RPC Out -> method:event | params:["HVL_java","Tradfri65539:1","WORKING",true]
Sun Sep 02 2018 21:31:45 GMT+0200 (CEST)[HomematicLogicalLayer] [DEBUG] - Device Value Change Event for Tradfri65539:1
Sun Sep 02 2018 21:31:45 GMT+0200 (CEST)[HomematicDevice] [DEBUG] - Channel Value event WORKING
Sun Sep 02 2018 21:31:45 GMT+0200 (CEST)[HomematicChannel] [DEBUG] - Parameter value change event WORKING
Sun Sep 02 2018 21:31:45 GMT+0200 (CEST)[HomematicChannel] [DEBUG] - Channel set Value WORKING to true
Sun Sep 02 2018 21:31:45 GMT+0200 (CEST)[HomematicDevice] [DEBUG] - Channel Value event LEVEL
Sun Sep 02 2018 21:31:45 GMT+0200 (CEST)[HomematicChannel] [DEBUG] - Parameter value change event LEVEL
Sun Sep 02 2018 21:31:45 GMT+0200 (CEST)[HomematicChannel] [DEBUG] - Channel set Value LEVEL to 0
Sun Sep 02 2018 21:31:45 GMT+0200 (CEST)[HomematicLogicalLayer] [DEBUG] - repl  >  
Sun Sep 02 2018 21:31:45 GMT+0200 (CEST)[HomematicLogicalLayer] [DEBUG] - rpc < setValue Tradfri65539:1,LEVEL,0`
- Debug Modus wieder beendet.
- Licht funktioniert wieder.

**Comment by cRemE-fReSh** [comment]
Die Story wird noch lustiger:
- Programm wieder auf 85% geändert.
- Lampe funktioniert.
- Debug Modus aktiviert. Lampe geht nicht mehr an.
- Debug Modus wieder deaktiviert. Lampe geht wieder an.

Es scheint so, als ob der Debug Modus da irgendetwas durcheinander bringt.

**Comment by cRemE-fReSh** [comment]
Es hat jetzt eine ganze Weile mit 85% funktioniert. Seit heute morgen nicht mehr. Geht nicht mehr an, noch aus. In der Homematic Seite steht drin, das Licht wäre 85% eingeschaltet, obwohl es ausgeschaltet ist. Steuerung nicht möglich.
Jetzt habe ich den Wert wieder auf 84% geändert. Jetzt funktioniert das Skript wieder.
