### ISSUE TITLE
HVL & Raspberrymatic 3.41.11.20181126

### ISSUE THREAD

**Issue by hauvol** [thkl/Homematic-Virtual-Interface#59]
HVL doesn't work with 3.41.11.20181126.

[https://github.com/jens-maus/RaspberryMatic/issues/492](url)

InterfacesList.xml  hat falsches Format, Zeilenumbrüche fehlen.
Welche Ports müssen seitens CCU offen sein? 31999 und ?

**Comment by AdlerCentauri** [comment]
Ich würde das unentbehrliche HVL auch gerne wieder ans laufen bekommen mit der aktuellen CCU FW.

**Comment by jens-maus** [comment]
Hier auch noch einmal der Hinweis das im optimalen Fall man keinerlei 3xxxx Ports in der CCU freigeben sollte (siehe https://github.com/jens-maus/RaspberryMatic/issues/492#issuecomment-441989452). HVL sollte also auf das Auswerten der InterfacesList.xml verzichten da hier nur die internen Ports vermerkt sind.

**Comment by AdlerCentauri** [comment]
Es ist ruhig um thkl geworden, auch im Forum war er schon lange nicht mehr online. Hoffentlich passiert da noch was, ich würde es mir wünschen. HVL ist echt ne super Sache.

Habe es seit erscheinen im Einsatz und es lief immer sehr gut, und wenn nicht, hat thkl schnell Abhilfe geschaffen.

@jens-maus seitdem es HVL gibt läuft das mit der  InterfacesList.xml so, bisher gab es da nie Probleme, ist das so schlimm bzw. sollte man es unbedingt anders lösen? Also ich frage nur weil es mir interessiert.

**Comment by jens-maus** [comment]
So ruhig ist es doch gar nicht (siehe https://github.com/thkl/Homematic-Virtual-Interface/commit/558e2b356782b8a297d929d5c59aeb9052a38e89). :) 
Er hat da bereits einen workaround für Firmware 3.41.x eingebaut. Allerdings empfinde ich den als recht schlechten workaround. Hier sollte besser so vorgegangen werden, das ganz auf das Auswerten der InterfacesList.xml verzichtet wird oder zumindest für die jeweiligen bekannten Interfaces (BidCos, HmIP, CUxD, etc.) feste ports angenommen werden und nicht die dort vermerkten URLs 1:1 so übernommen werden wie das wohl gerade in HVL der Fall ist. D.h. man sollte auch nicht via eines ReGa-Skriptes aus der Ferne versuchen die Interfaces abzufragen. Das ist und war noch nie der offizielle Weg und das fällt HVL nun eben gerade auf die Füße.

**Comment by AdlerCentauri** [comment]
Ach das habe ich noch garnicht gesehen, cool das es weitergeht.

Also ich verstehe nur so halb was du meinst. Wenn @thkl das hier liest, weiß er dann was du meinst bzw. weiß es dann durch deinen text wie er es "richtig" machen sollte?

Wie gesagt, ich bin absolut überzeugt von HVL und froh das es es gibt. Daher wäre es nur cool, wenn es in Zukunft auch vernünftig läuft. Bzw. bei mir ist ja es wie gesagt immer vernünftig gelaufen.

**Comment by thkl** [comment]
Haaaaalt :
Die Auswertung der Interfaces.xml erfolgt nur zu dem Zweck des Tests ob das eigene HVL Interface da ist. 

Die CCU (also Rega) macht nach dem Boot einen Init auf die HVL Adresse. Liefert da aber seit neuestem xml_rpc://127.0.0.1:31999 als callback URL. Dort ist aber augenscheinlich keiner zu Hause. Deswegen der Stunt mit Port - 30000 ....

**Comment by jens-maus** [comment]
Klar wird er wissen was ich meine :)

Im übrigen hat das alles auch nichts mit RaspberryMatic zu tun. Das selbe Problem tritt auch mit einer CCU3 auf. Und ja, das alles liegt daran das  es mit der 3.41.x firmware verbesserte Sicherheitseinstellungen (Firewall&Authentifizierung) gibt.

**Comment by jens-maus** [comment]
@thkl Ah, nun verstehe ich :) Kannst du dazu bitte mal den response payload zeigen damit ich das nachvollziehen kann?

**Comment by AdlerCentauri** [comment]
Hi @thkl, es freut mich von dir zu hören :-)

@jens-maus, klar, habe nur RM geschrieben weil ich die schon seit ewig nutze :-)

**Comment by thkl** [comment]
@jens-maus den Payload des Init Requests von Rega nach dem Boot ? 

Ja ich lebe noch, viel Arbeit wenig Zeit :) und noch wenig davon, um sie in einem Forum zu verbrennen. 😀

**Comment by jens-maus** [comment]
@thkl Ja, bitte mal deinen XMLRPC Request und die Antwort darauf zeigen.

Und das auf :31999 keiner zuhause ist stimmt eigentlich nicht ganz. die gemeldete URL referenziert ja auf 127.0.0.1 und innerhalb der CCU lauscht Rega sehr wohl auf Port 31999 am 127.0.0.1 interface. D.h. du solltest IMHO erst gar nicht die callback URL dort auswerten und dann auch noch so einen Stunt mit -30000 versuchen, sondern du weisst ja von vorn herein das du mit der ReGa sprichst und diese IMMER auf port 1999 zu finden ist und mit der gleichen IP wie dein request rausging.

**Comment by AdlerCentauri** [comment]
> @jens-maus den Payload des Init Requests von Rega nach dem Boot ?
> 
> Ja ich lebe noch, viel Arbeit wenig Zeit :) und noch wenig davon, um sie in einem Forum zu verbrennen. 😀

Viel Arbeit ist immer gut. Aber danke das du hier weiter machst.

**Comment by thkl** [comment]
Doch ich muss auf die Callbacks hören. Denn der selbe Init kommt von HMServer (groups) daher ist das schon ok.  Ich wollte mit Absicht keine festen Ports nehmen. Wenn man schon der Antwort von Rega nicht trauen kann, wem dann 😃 ... und ja ich verstehe den Zusammenhang mit internen Sports und dem was die Firewall rauslässt :)

**Comment by jens-maus** [comment]
Wie gesagt, ich kann nur noch einmal anraten das auf feste Ports umzustellen denn sollten die internen Ports noch einmal umgestellt werden wird dein "-30000" workaround wieder schiefgehen. Auf die Callbackurls kann man sich defakto als externe Applikation nicht verlassen.

**Comment by thkl** [comment]
Aber eigentlich ist diese Callback URL laut Doku das wo man antworten soll. Bzw wenn ich ein Init auf ein Interface mache, muss ich die ja auch mitliefern. 

Die sauberste Lösung wäre, wenn Rega eine gültige Callback URL zurückliefen würde.

**Comment by thkl** [comment]
Aaaaaah https erzwingen und kaputte Zertifikate.  Don’t ich glaubt ich schmeiß den Kram gleich weg. (Sorry geht gleich wieder)

**Comment by jens-maus** [comment]
:) Wieso "kaputte Zertifikate" bzgl. https erzwingen?!?! Vor was hast du denn Bedenken?

**Comment by thkl** [comment]
Die Zertifikate sind selbst signiert. Damit ist die Chain of Trust kaputt. Das hatten wir schon mal. 
Ja, geht alles TLS damit ist besser als kein TLS. 
Aber ich muss dann als Client wieder Exceptions zulassen.  Wenn ich mich nicht auf das Zertifikat verlassen kann, wie soll ich dann „Man in the middle“ erkennen. Ich würde die Authentifizierung sowieso über oauth oder eine Tokenlösung abfrühstücken. Und ganz darauf verzichten das man der Maschine auf der anderen Seite permanent seine Credentials geben muss. 

Aber das ist ein anderes Thema. 

Ich werde einfach die Ports fest einstellen. Mit einem override aus der config.  Dann kann man das ggf überschreiben. 

Und ja, Rega Calls können seit dem letzten Commit auch schön mit der Authentifizierung umgehen.

**Comment by jens-maus** [comment]
Natürlich muss man (genauso wie Webbrowser das machen) Optionen hinzufügen um sagen zu können das ein selbst signiertes Zertifikat im Einsatz ist und er entweder die Chain of Trust ab einer gewissen Tiefe ignorieren soll, oder man erlaubt das Zertifikat entsprechend herunterzuladen und als "Sicher" zu definieren damit man in the middle Attacken ausgeschlossen werden können falls das Zertifikat sich mal ändert. Alles ein wenig aufwand natürlich, aber kein Hexenwerk und auch nicht unsicher am Schluss. Und das https erzwungen wird, wird natürlich kein default werden sondern optional. Jedoch wird dann eben das anschalten der Authentifizierung mit einem erzwingen von https verknüpft werden da ansonsten man die authentifizierung auch komplett sein lassen kann weil ja sonst jeder mitlesen kann welche credential es sind.

Und gut das du die Ports nun fest verdrahten willst, das sollte der sicherste Weg sein. 👍

**Comment by thkl** [comment]
Deswegen das eigene WLAN als per default sicher erklären und den ganzen TLS und Auth Schmonz weglassen. ....😜

**Comment by jens-maus** [comment]
So handhabe ich das natürlich selbst auch, aber "unsere Freunde" die "IT-Sicherheitsexperten" sehen sowas eben anders und verfluchen ansonsten die CCU weiterhin :-)

**Comment by thkl** [comment]
Wäre iÜ toll von Seiten der "Security Freunde", wenn solche Änderungen mal irgendwie vorher mal an die Leute die sich dann damit rumschlagen müssen pulbliziert werden würden. Ich rede her von den Freunden bei eq3...

**Comment by jens-maus** [comment]
Und was hätte das geändert? ;)

**Comment by thkl** [comment]
Die Änderungen (nicht nur hier sondern zb auch im HomeBridge Modul) wären vor dem Release der FW drin. Und niemand müsste Tickets auf machen ....

**Comment by jens-maus** [comment]
Das wäre nicht garantiert gewesen denn die Komplexität und das Verständnis hätten ggf. dazu geführt das es ohnehin nicht zu 100% klar gewesen wäre was genau diese Sicherheitseinstellungen verändern. Das einzige was etwas gebracht hätte wäre eine public beta version.
Aber auch da wäre der Aufschrei groß gewesen. Ergo muss man halt auch sagen, dass die Leute die trotz größerer Warnung (und die steht im CCU Firmware ChangeLog) direkt geupdatet haben zum teil eben besser hätten etwas warten sollen und nicht immer auf die aktuellsten Versionen gehen müssten wenn entweder das technische KnowHow nicht da ist oder das System so kritisch ist das man nicht ein paar Wochen mit eingeschränkten Funktionen (vor allem im Bezug auf externe Anwendungen) leben kann. Aber lassen wir das, GitHub ist ja kein Diskussionsforum :)

**Comment by AdlerCentauri** [comment]
Ist es denn wichtig, dass die Formatierung in der InterfacesList.xml für den Eintrag für HVL auch korrekt ist? Weil jetzt ist er ja laut @jens-maus nicht korrekt formatiert. Oder ist der Eintrag mit der kommenden HVL Version garnicht mehr notwenig?

**Comment by thkl** [comment]
Der Eintrag wird benötigt, damit Rega auf der CCU mit HVL reden möchte.
Die Formatierung sollte aber 🌭sein. Denn das ist valides XML was jede normale XML lib versteht.

**Comment by jens-maus** [comment]
@thkl Das gilt zwar für die ReGa, aber es gibt an verschiedenen Stellen in der WebUI Routinen die die InterfacesList.xml auch parsen und dafür keinerlei XML parser verwenden sondern line-basiert nach dingen suchen ohne xml zu beachten. Es wäre daher ratsam die InterfacesList.xml bitte (wenn diese schon ergänzt wird) mit der gleichen Anzahl an newlines und Tabulatoren/spaces auszustatten bei den eintragen die hinzugefügt werden.

**Comment by thkl** [comment]
![](https://media.giphy.com/media/Pn1gZzAY38kbm/giphy.gif)

CUxD macht das iÜ genauso ...

**Comment by AdlerCentauri** [comment]
Meine sieht so aus
`<?xml version="1.0" encoding="utf-8" ?> 
<interfaces v="1.0">
	<ipc>
	 	<name>BidCos-RF</name>
	 	<url>xmlrpc_bin://127.0.0.1:32001</url> 
	 	<info>BidCos-RF</info> 
	</ipc>
	<ipc>
	 	<name>VirtualDevices</name>
	 	<url>xmlrpc://127.0.0.1:39292/groups</url> 
	 	<info>Virtual Devices</info> 
	</ipc>
	<ipc>
	 	<name>HmIP-RF</name>
	 	<url>xmlrpc://127.0.0.1:32010</url> 
	 	<info>HmIP-RF</info> 
	</ipc>
	<ipc>
	 	<name>CUxD</name>
	 	<url>xmlrpc_bin://127.0.0.1:8701</url> 
	 	<info>CUxD</info> 
	</ipc>
<ipc><name>HVL</name><url>xmlrpc://192.168.191.40:7000</url><info>HVL</info></ipc></interfaces>
`

**Comment by jens-maus** [comment]
@thkl Was meinst du genau?

**Comment by thkl** [comment]
@jens-maus na das ich dem Rega sagen kann leg mir mal bitte ein Interface mit der URL ..... und er Info .... an ... dann muss ich nicht will in Dateien schreiben, die mich nichts angehen ... der Rega kann dann gleich einen DOM Reload machen und einen init call drauf machen. Spart man sich auch den Reboot der CCU

**Comment by jens-maus** [comment]
@thkl Ich weiss immer noch nicht was du meinst? Es gibt solch eine Funktion meines Wissens nicht. Jeder muss selbst in der InterfacesList.xml Datei ablegen was er gerne will. Die Datei ist ja per se auch keine ReGa Datei sondern eine generelle Schnittstellenbeschreibungsdatei.

**Comment by thkl** [comment]
@jens-maus eben deswegen die Frage wo ich für so eine neue Funktion einen Change Request machen muss .. oder sind die Rega Funktionen in Stein gemeisselt und keiner fasst das mehr an. 
"Never ever touch an running System Style ..."

**Comment by jens-maus** [comment]
@thkl Na wenn, dann bei mir bzw. im RaspberryMatic GitHub Tracker. Allerdings hilft das nicht für ältere Systeme, etc. Deshalb ja auch mein Hinweis das du bitte die Art&Weise änderst wie du da dein xml reinschreibst. Bitte verwende Spaces/Tabs/NewLines in genau der gleichen Anzahl und Art wenn du die HVL Einträge da reinmachst.

**Comment by AdlerCentauri** [comment]
Also so wie ich das verstehe, möchte er mit einem Befehl den entsprechenden Eintrag in die InterfacesList.xml eintragen, damit das nicht manuell gemacht werden muss, sondern automatisch geschieht sobald man HVL installiert und man dann auch nicht mehr die CCU rebooten muss.

Irgendwie so verstehe ich das ^^

**Comment by thkl** [comment]
Ich schreibt es mit auf die Liste

**Comment by TheRoolBool** [comment]
@thkl wann ungefähr kann man mit dem update rechnen? Und danke das es hier weiter geht.

**Comment by coolsurfer** [comment]
Das mit dem - 30000 beim Port halte ich auch nicht für sinnvoll, denn mein xmlRPCServer macht einen separaten INIT auf HMVI und dort ist der Port immer grösser als 30.000 was aber auch so beabsichtigt und korrekt ist. Hier muss als entweder durch HMVI geprüft werden, ob HMVI dem Port vertrauen kann, weil sich ein Scrip an die Spezifikation hält, oder eben nicht, weil es ein init der CCU ist der unsichtbar geproxied wird.

**Comment by thkl** [comment]
Naja die Frage ist wie bekomme ich raus, welcher Call von wo kommt.  Dafür ist ja eigentlich die URL in dem Init Call da.

**Comment by coolsurfer** [comment]
Ohne es geprüft zu haben; evtl. über die "callbackid" - das ist zwar auch nicht reichlich zukunftssicher aber evtl. hat ja @jens-maus eine Idee wie man den "fehlerhaften" init-call der CCU eindeutig erkennen kann

**Comment by coolsurfer** [comment]
Bis dahin vielleicht an die Stellen den Port fest auf 1999 an denen du ohnehin die CCU-IP-Adresse durch den Host-Namen der Config ersetzt ?

**Comment by thkl** [comment]
Die Callback ID ist variabel laut Doku. 
Rega schickt eine 4 Stellige Zahl.  Der HM Sever immer irgendwas mit Java.  

Darauf kann ich nicht zählen ...

**Comment by thkl** [comment]
Ne, ich kann den Port nicht fest setzten.  Denn ich bekomme aus der CCU 2 Inits.  Wie schon oben geschrieben. Einen von Rega und einen vom HM Server. Ich muss mal schauen, ob ich ggf eine Art Übersetzungstabelle nutzen kann. Also 127.0.0.1:1999 -> ccuhost:1999
127.0.0.1:31999 -> ccuhost:1999

Usw. 

Der Idealfall wäre wenn die Callback Url korrekt wäre.

**Comment by JensBonse** [comment]
Also das eine Callback URL auf den Loopback Adapter zeigt ist meiner Meinung nach absolut unüblich.
Und ein XML nur richtig parsen zu können, wenn die TABs, Leerzeichen und Zeilenumbrüche OPTISCH schön sind hört sich für mich nach einer Bastellösung an.

**Comment by thkl** [comment]
😀 die Rega Leute haben halt nie damit gerechnet , das jemand ihr Protokoll benutzt und außerhalb der CCU im Netzwerk ein Interface betreibt.  ¯\_(ツ)_/¯

**Comment by jens-maus** [comment]
@thkl Das hast du vollkommen richtig erkannt. Ich kann auch leider nicht erkennen wie ich im Nachhinein die callback url anders machen könnte in ReGa&Co damit sie auch abwärtskompatibel ist. Wenn einer eine Idee hat, her damit :)

**Comment by jens-maus** [comment]
@JensBonse Sagen wir mal so, es war schon initial falsch XML zu verwenden :), denn hast du mal probiert ein xml mittels shell skript sauber zu Parsen, das wir ein großes unterfangen...

**Comment by coolsurfer** [comment]
@jens-maus kannst du einen "undokumentierten" weiteren Ast im Response-XML einfügen, der dann eben eine ExternalCallbackUrl enthält, so dass beide URL-Adressen im Response sind. Das bleibt abwärtskompatibel und externe Schnittstellken müssen sich dann nur noch einmal anpassen :-)

**Comment by thkl** [comment]
@Jens-Maus na das ist einfach. Wenn aus der Interface.xml ein 127.0.0.1 als Host kommt dann Callback auf 127.0.0.1 wenn nicht dann auf die eigene LAN Schnittstelle.

**Comment by jens-maus** [comment]
Wie schon vorher bereits mehrfach gefordert. Zeig mal bitte deinen gesamtem XMLRPC payload für solch ein Beispiel

**Comment by coolsurfer** [comment]
@jens-maus: Ich hoffe das trifft auch auf HMVI zu; aber das ist das, was ich (mit einem anderen Connector) aus der CCU bekommen, falls es bei dir anders sein sollte @thkl korrigiere mich bitte:

<?xml version="1.0"?>
<methodCall>
<methodName>init</methodName>
<params>
<param>
<value>xmlrpc://127.0.0.1:31999</value>
</param>
<param>
<value>1234</value>
</param>
</params>
</methodCall>

das ist die Antwort darauf:

<?xml version="1.0" encoding="ISO-8859-1"?><methodResponse><params><param><value></value></param></params></methodResponse>

**Comment by bvol** [comment]
pragmatischer Ansatz: die neue Version nicht abwärtskompatibel gestalten. Wer HVL nutzen will, darf doch bitte gleich noch von Jens' Arbeit profitieren.... Und wenn's dann wirklich der alte Kram sein soll, dann einfach eine alte Version über git ziehen?!? Wär das nicht eine Option? Weder  Jens noch Thomas sollen hier doch unlösbare Probleme mit solch enormen Zeitaufwand lösen.

Wenn ich auf der 3.41 bin, was ich sicher sein werde, wenn Thomas auch noch den KS550er Bug gelöst hat, dann interessiert es mich doch herzlich wenig, ob HVL mit einer alten Version von Homematic kompatibel ist.

**Comment by coolsurfer** [comment]
@bvol das wird so nicht funktionieren, weil es geht nicht daraum, dass HMVI zwischen "alt" und "neu" unterscheiden muss sondern zwischen "kommt von der CCU" oder "kommt von woanders", weil sich "woanders" eben an die Spezifikation hält und die CCU nur so ein bischen daran :-)

**Comment by bvol** [comment]
ist ja gut....

**Comment by bvol** [comment]
@thkl hast Du mal die `cat /etc/lighttpd/conf.d/proxy.conf` geparsed? Ich glaub, das steht die gewünschte Info drin.

**Comment by thkl** [comment]
jain .. denn ich bekomme vom HM Server einen 2. Init Call:

`<?xml version="1.0" encoding="ISO-8859-1"?><methodCall><methodName>init</methodName><params><param><value>http://127.0.0.1:39292/bidcos</value></param><param><value>HVL_java</value></param></params></methodCall>`

**Comment by thkl** [comment]
@bvol zum Thema Proxy.conf .. da HVL nicht auf der CCU läuft (also nicht zwingend) ist das keine Option. Ich mach schon Stunts mit dem Parsen der Interfaces.xml um meinen eigenen Interfacenamen zu ermitteln. Aber hier müsste ich auch wieder Rega und einen Exec Call misshandeln um die Daten aus der CCU zu lesen ...

**Comment by bvol** [comment]
@thkl nur für mein Verständnis, wer initialisiert den request? die CCU oder HVL? Ich würde mich dann tatsächlich mal mit der Reverse Proxy Thematik der CCU beschäftigen... Wenn HVL den Request gegen die CCU absetzt und die CCU dann murks zurückliefert kann man das sicher mit einer Rewrite Regel auf dem lighttp korrigieren.

**Comment by thkl** [comment]
@bvol die CCU ... HVL ist als Interface in der Interfaces.xml eingetragen. Beim Start von Rega ließt dieser die Datei und macht einen Init Call an alle dort eingetragenen Interfaces ... HVL bekommt den Init Call, merkt sich die CallBack ID und schickt alle Events über geänderte Geräteparameter ab diesem Zeitpunkt an die im Init Call stehende Callback URL ...(die ich umbauen muss, um die CCU zu erreichen) ... die Parameter des Init Calls speichere ich auch für den Fall das HVL neu startet. Dann kann ich weiter Events senden, ohne das die CCU neu booten muss, denn die CallbackID ist ja weiter gültig.

**Comment by thkl** [comment]
Ich verstehe das Problem, was @jens-maus hat. Für Rega ist es ok das da 127.0.0.1:31999 steht.
Denn diese URL ist innerhalb der CCU erreichbar. Von außen wird der Port 31999 nur durch die FW geblockt. Bzw wird 1999 durch lighthttp auf den neuen RegaPort 31999 umgeleitet.

Rega müsste erkennen ob er einen Init Call an 127.0.0.1 (localhost) macht, oder an ein Interface außerhalb localhost und dementsprechend seine Callback URL so mitliefern, das sie valide ist.

**Comment by jens-maus** [comment]
Das geht hier langsam zu weit und zu sehr in die breite. Der Punkt ist einfach das die URL die via init mitgeteilt wird von ReGa oder von HMIPServer schon die richtige ist und auch der Port (3xxxx) ist im Prinzip der richtige port. Aber eben nur wenn die Applikation die das init empfängt selbst auf der CCU betrieben wird und es da eben 127.0.0.1 gibt und auch den offenen 3xxxx Port. Für externe Applikationen ist das nicht der Fall und es gibt momentan einfach keine Möglichkeit das die ReGa oder HMIPServer, oder CUxD bei dem init die URL für *externe* Anwendungen anders ausliefert und dann eben statt 127.0.0.1 die IP-Adresse von eth0 nimmt und statt des rein internen 3xxxx port eben der externe xxxx port. Das müsste nun für jeden dieser Schnittstellenprozesse nachgepatcht bzw. abgeändert werden und das ist zwar theoretisch möglich, praktisch aber eher nicht da dies ja auch CUxD und andere potentielle Schnittstellenprozesse betreffen könnte betreffen könnte. Das XMLRPC vom RFD wird ja vmtl. genau gleich reagieren. Es bleibt also vmtl. nichts anderes üblich das die externen Anwendungen eben selbst eigene Intelligenz darin stecken zu identifizieren mit WEM sie gerade reden und wie sie die URL abzuändern haben damit diese für ihre Anwendung passen. Also @thkl hat hier schon prinzipiell recht. Das CCU Ecosystem war nie davon ausgegangen das es externe Anwendungen im LAN gibt die von aussen events schicken könnten sondern ist immer davon ausgegangen (und das tut es noch immer) das Anwendungen immer auch auf dem 127.0.0.1 interface laufen auf der selbe Maschine wie ReGa, HMIPServer & Co.

**Comment by thkl** [comment]
Jain, ... schuldige sind die Logikschichten (REGA und HMServer) diese haben Init nicht so implementiert, wie es die Doku festschreibt. Ich werde eine Übersetzungstabelle mitliefern, die kann dann auch jeder anpassen, wenn selber Änderungen gemacht wurden.

**Comment by jens-maus** [comment]
Ich werde aber trotzdem mal in ReGa schauen ob ich in kompatibler weise vielleicht zumindest dafür die callback URL in einfacher art für externe Anwendungen anders ausliefern lassen kann.

Wer ausser ReGa und HMIPServer schickt denn noch basierende auf der InterfacesList.xml ein init momentan an externe Anwendungen raus?

Und übrigens @thkl: `xmlrpc_bin` ist nicht generell obsolete, sondern lediglich für externe Anwendungen weil lighttpd das nicht als proxy bedienen kann (muss HTTP basiert sein). D.h. auch `xmlrpc_bin` geht wenn man auf 127.0.0.1 sitzt, aber eben nicht wenn man eine externe app ist wie HVL.

**Comment by bvol** [comment]
@jens-maus wäre es denn für Dich möglich, die Mappings aus der /etc/lighttpd/conf.d/proxy.conf für Daus irgendwo auf dem WebUi rauszuschreiben, so dass auch Dummys ggf. die Konfiguration auf HVL entsprechend anpassen können?

**Comment by thkl** [comment]
@jens-maus soweit ich weiß niemand außer rega und hmserver innerhalb der ccu, denn das sind die einzigen Logikschichten ... CuxD ist, wie HVL, ein Interface ...

Und ja, natürlich geht xmlbin weiter, nur blöderweise nicht von Außen. (Ich verstehe warum, lighthttp wird hier als universeller Gatekeeper und HTTPS Tunnel (miss/ge)braucht). Dann sollte aber auch der Init Call nicht xmlbin liefern ... 

(ich bin schon ruhig ... :) )

**Comment by iBoarder** [comment]
Funktioniert mittlerweile eigentlich die Roku wenn man HVL als AddOn direkt auf der CCU installiert? Das ging ja (bisher?) nicht weil die beiden sich wegen dem SSDPD Dienst in die Quere gekommen sind. 

@thkl wollte sich ja mal mit @jens-maus (bzw. beide) zusammen hinsetzen damit die Roku auch läuft wenn HVL direkt auf der CCU installiert ist. Nur wegen der Roku habe ich HVL im Moment extern installiert. Gibt es dazu was neues? Das wäre auch Mega wenn das mittlerweile oder in Zukunft läuft.

**Comment by thkl** [comment]
@bvol man kann sich das Proxy File schon über Rega liefern lassen, darüber kann ich mir (fast) jedes File aus der CCU schicken lassen, das ist kein Akt. Aber das ist der falsche Ansatz ...
Genau wie das Erweitern der Init Response, wer weiß ob die anderen Interface Prozesse dann damit klar kommen.

Wie geschrieben, ich schau mal, ob ich das eleganter (also -30000 [was zugegebenermassen der quick and dirty fix war]) lösen kann.

**Comment by bvol** [comment]
@thkl Achtung: proxy.conf ist kein XML :-)

**Comment by thkl** [comment]
@iBoarder  nein, denn die CCU selber macht announct sich per UPNP und daher kann ich keine eigenen Dienste mehr rausblasen ... ist halt so ... das würde ich auch nicht ändern wollen, da HVL ein Addon ist und nicht die CCU Aufgaben übernehmen soll ...

**Comment by AdlerCentauri** [comment]
Oh ja das die Roku läuft wenn HVL direkt auf der CCU installiert ist, wäre ein Traum. HVL zusammen mit der Roku und der Harmony ist einfach ein Traum. Den Roku als gerät in der Harmony und die schaltet direkt den Zwischenstecker ein wenn eine Aktion auf der Harmony gestartet wird 😍

**Comment by thkl** [comment]
> Oh ja das die Roku läuft wenn HVL direkt auf der CCU installiert ist, wäre ein Traum. HVL zusammen mit der Roku und der Harmony ist einfach ein Traum. Den Roku als gerät in der Harmony und die schaltet direkt den Zwischenstecker ein wenn eine Aktion auf der Harmony gestartet wird 😍

No Way ...

**Comment by AdlerCentauri** [comment]
Ok, ist ja auch kein Problem wenn es extern läuft. Klappt alles wunderbar.

**Comment by jens-maus** [comment]
ssdpd lösst schon seit geraumer Zeit einen zweiten UPnP Announcee neben sich zu. Wenn der andere sich also auch konform verhält sollte das also eigentlich gehen ohne das ssdpd gestoppt werden muss

**Comment by AdlerCentauri** [comment]
Bisher geht es leider nicht (ich habe die Änderungen ssdpd auf der RM verfolgt). Das Roku Device wird in der Geräte-WLAN-Suche in der Harmony App nicht gefunden. 

Wenn HVL extern z.B. auf einem Pi läuft, dann wird das Roku Device  in der Geräte-WLAN-Suche in der Harmony App sofort gefunden.

**Comment by thkl** [comment]
wie auch immer ich höre auf Port 1900 auf upd Broadcasts mit M-SEARCH * Messages.

**Comment by bvol** [comment]
@jens-maus und @thkl : Beim Abendbrot noch 'ne Idee gehabt: 

Wenn die CCU initial einen http request an den HVL schickt, können wir ja doch die Homematic Logik verwenden und die Anfrage via Localhost und reverse Proxy auf den HVL schicken. Somit wäre in der interfaces.xml nur noch 127.0.0.1: zu definierender lighttp port einzutragen und die in der proxy.conf packen wir einen Eintrag 'rein, der dann auf HVL zeigt. Somit könnten wir den init string mit der richtige IP und dem richtigen Port an HVL senden. Somit müsste HVL nicht die interfaces.xml abgrasen, der init string würde korrekt an HVL gesendet werden und wir wären eigentlich dort, wo wir sein wollen?!? Wenn ich die Doku zu lighttp richtig verstehe, dann müssten wir noch nicht einmal die proxy.conf anfassen, sondern einfach eine zusätzliche hvl_proxy.conf ins vonfig Verzeichnis packen.

Was meint Ihr zu dem Vorschlag?

**Comment by bvol** [comment]
ist die replacement Table schon im NPM drin? Ich würd dann nochmal testen.

**Comment by thkl** [comment]
nein für den neuen core gibt es noch keine neue npm Version.

**Comment by AdlerCentauri** [comment]
Also bleibt die Version auf Version 0.2.67? Und beim WeatherUnderground Plugin wird mit das Update noch nicht angezeigt, Version 0.0.6

**Comment by thkl** [comment]
Naja irgendwann in Kürze werde ich den wohl mal updaten aber nicht heute

**Comment by bvol** [comment]
@thkl und @jens-maus : ich bin jetzt mit meiner produktiven Umgebung auf 3.41.11.20181126 gegangen und habe HVL manuell auf 0.2.68 gepatched. Funktioniert alles. Danke nochmals für Euren Einsatz hier! Gruss Volker

**Comment by AdlerCentauri** [comment]
Das ist super das alles funktioniert. 

Danke für die Arbeit!

@thkl, wann kann man offiziell mit dem Update rechnen?

**Comment by thkl** [comment]
Doch, aber siehe Beschreibung des commits  ( https://github.com/thkl/Homematic-Virtual-Interface/commit/4a2dc2f7116c2c4affee58d83973190bd4ddaaa4 ) das .dev File muss gelöscht werden. Damit HVL die Gerätedefinition neu ließt und das Gerät mit den geänderten Parametern an die CCU schickt.

**Comment by AdlerCentauri** [comment]
Welches von den oberen soll das sein? :/ Leider steht da nichts von KS500 dabei
<img width="247" alt="bildschirmfoto 2018-12-02 um 12 15 55" src="https://user-images.githubusercontent.com/37038767/49339058-18363600-f62c-11e8-8403-f630e77e2c45.png">

**Comment by AdlerCentauri** [comment]
WeatherUnderground, aber auch davon sehe ich nichts. Siehe die Liste oben.

**Comment by bvol** [comment]
und im WebUi von HVL siehst Du auch nix, wenn Du links auf Weatherunderground klickst? Bei Netatmo sehe ich dann auf der rechten Seite im WebUi die generierten Gerätenamen.

**Comment by AdlerCentauri** [comment]
<img width="1160" alt="bildschirmfoto 2018-12-02 um 14 42 28" src="https://user-images.githubusercontent.com/37038767/49340468-838a0300-f640-11e8-9ca5-d4fcfe185aba.png">

**Comment by bvol** [comment]
siehst Du in der CCU eine Seriennummer für die Wetterstation?

**Comment by AdlerCentauri** [comment]
@bvol Hast Du noch eine Idee?

**Comment by bvol** [comment]
ich hab bei mir festgestellt, dass ich mit den „alten“ durch die 0.2.66 er Version generierten hvl devices so seltsame probleme hatte. Daher bin ich radikal vorgegangen, habe alle plugins im hvl deaktiviert, alle noch auf der ccu vorhandenen devices (natürlich nur die, die via hvl generiert waren) über ‚delete device‘ im hvl auf der ccu gelöscht und dann auf dem pi hvl gestoppt, alle .dev aus dem verzeichnis gelöscht, pi durchgebootet und ein plugin nach dem anderen wieder aktiviert und neu über den ccu posteingang wieder integriert. Ging bei mir so problemlos, da ich die HVL geräte in keinen programmen verwendet hatte.

Radikaler Ansatz, aber jetzt funktionieren alle hvl devices auf der ccu problemlos und werden auch wieder in pocket control auf dem iphone richtig angezeigt.
