### ISSUE TITLE
Wie den Fix für die neue Raspberrymatic Version einspielen?

### ISSUE THREAD

**Issue by capitaenz** [thkl/Homematic-Virtual-Interface#61]
Hallo thkl,

wie installiert man die gefixte Version von HVL?
Einfach "Clone or download" - "Download ZIP" und dann die "hvl-rasb-0.0.7.tar.gz" drüberinstallieren über "Zusatzsoftware installieren / aktualisieren" ?
Leider funktioniert der Downloadlink nicht mehr -> 404 not found

Danke und VG
Leif

**Comment by thkl** [comment]
das npm wurde gerade auf 0.2.67 gehoben. Der interne Updater sollte das in Kürze erledigen
