### ISSUE TITLE
"Alle Verbindungen entfernen" entfernen funktioniert nicht

### ISSUE THREAD

**Issue by AdlerCentauri** [thkl/Homematic-Virtual-Interface#63]
Hallo,

wenn man in der HVL WebUI auf "Alle Verbindungen entfernen" klickt, dann sieht die Ansicht danach so aus:
<img width="1197" alt="bildschirmfoto 2018-11-27 um 22 08 35" src="https://user-images.githubusercontent.com/37038767/49111809-757b6180-f291-11e8-93da-c2a67c3a3ba8.png">

Die CCU wurde trotzdem mal neu gestartet, aber das Interface bzw. die Verbindung wurde nicht entfernt.

Wenn man dann in der HVL WebUI wieder oben links auf "Home" klickt, dann sieht die Ansicht wieder so aus:
<img width="1148" alt="bildschirmfoto 2018-11-27 um 22 13 24" src="https://user-images.githubusercontent.com/37038767/49111891-acea0e00-f291-11e8-913b-5b7a2d0034e0.png">
Die Verbindung wird also tatsächlich nicht entfernt.

Aktuell installierte HVL Version 0.2.67

Das Problem bestand aber auch schon mit der HVL Version 0.2.66. In dieser Version habe ich auch schon mal versucht die Verbindung zu entfernen.

**Comment by JensBonse** [comment]
@thkl Kannst du uns mal verraten, wo in der CCU überall die Verbindung zu HVL hintelegt werden?
Ich habe auch mal versucht HVL zu deinstallieren und habe es aus der Interfaces.xml rausgeholt (habe die dann auch mal schön formatiert). Jedoch funktionierten die per HVL eingebundenen Dinge immernoch über die CCU trotz reboot dieser.

**Comment by thkl** [comment]
auf der CCU wird das nur in die Interfaces.xml geschrieben.
Rega legt jedoch einen Eintrag in seinem eigenen DOM an.

`
string ifName = "HVL";
string sifId; foreach(sifId, root.Interfaces().EnumIDs()){
object oIf = dom.GetObject(sifId);
WriteLine(oIf.Name());
if (oIf.Name()==ifName) {
 Write("Remove " # ifName);
 dom.DeleteObject(sifId);
}
}
`

Sollte das lösen ... (Keine Gewähr für irgendwas ;o) )
