### ISSUE TITLE
HVL 2.67 KS550 - Status "update" - 3.41.11.20181126

### ISSUE THREAD

**Issue by bvol** [thkl/Homematic-Virtual-Interface#64]
Moin Thomas
danke für den Fix für die 3.41. Ich hab' die 2.67 bei mir auf meinem Testpi mit Test Raspberry Matic und Netatmo Plugin am laufen. Soweit funktioniert alles, bis auf den KS550, dem irgendwie alle Details fehlen (siehe Screenshots). Kannst Du da bitte auch noch einen Blick drauf werfen?

Zudem zeigt er den Status "update".

Danke und Gruss Volker
![bildschirmfoto 2018-11-28 um 05 51 44](https://user-images.githubusercontent.com/45370257/49129973-0a9e4a80-f2d2-11e8-9f56-edf291286514.png)
![bildschirmfoto 2018-11-28 um 05 52 05](https://user-images.githubusercontent.com/45370257/49129974-0b36e100-f2d2-11e8-9547-0edd5bda723e.png)

**Comment by AdlerCentauri** [comment]
Kann ich bestätigen
<img width="987" alt="bildschirmfoto 2018-11-28 um 14 58 52" src="https://user-images.githubusercontent.com/37038767/49156714-4e1ea600-f31e-11e8-87fa-274393bdb958.png">

![fullsizeoutput_c60](https://user-images.githubusercontent.com/37038767/49156722-54148700-f31e-11e8-925e-13618090cd77.jpeg)

![fullsizeoutput_c5f](https://user-images.githubusercontent.com/37038767/49156732-5a0a6800-f31e-11e8-9570-befdc0395b96.jpeg)

**Comment by bvol** [comment]
top, getestet funzt.
