### ISSUE TITLE
Hue Gruppen Gerät wird nicht ausgeschaltet wenn einzelne Lampe ausgeschaltet wird

### ISSUE THREAD

**Issue by AdlerCentauri** [thkl/Homematic-Virtual-Interface#66]
Hallo,

wenn ich die Hue Gruppe einschalte, dann gehen alle sich in der Gruppe befindenden Hue Lampen an, wenn man die Lampen dann einzeln ausschaltet, dann bleibt das Status der Gruppe auf "Ein" bzw. dem Dimmwert stehen.

Dimmwert 100% bzw. ein
![hue_ein](https://user-images.githubusercontent.com/37038767/49171111-0d368980-f33e-11e8-923b-3b2716136d2b.gif)

Willkürlicher Dimmwert, hier 43%
![hue_43](https://user-images.githubusercontent.com/37038767/49171133-1d4e6900-f33e-11e8-95c1-11ba6d321afa.gif)

**Comment by thkl** [comment]
Das ist so.. Ich leite hier nur die aus der Hue Bridge kommenden Werte an die CCU. Die Gruppe in der Bridge scheint nicht aktualisiert zu werden, wenn man einzelne Lampen bedient.

**Comment by AdlerCentauri** [comment]
Daran kannst du nichts machen?

**Comment by thkl** [comment]
nö
