### ISSUE TITLE
Wenn auf den Hue Lampen einzeln eine Farbe gesetzt wird, wird diese nicht an die Gruppe übermittelt

### ISSUE THREAD

**Issue by AdlerCentauri** [thkl/Homematic-Virtual-Interface#67]
Hallo,

wenn man auf den Hue Lampen einzeln einen Farbwert (allen den selben Farbwert) setzt, dann wird dieser Farbwert nicht an die Hue Gruppe übergeben.

(Den Farbwert auf die einzelnen Lampen habe ich in einem Programm festgelegt und mit einer App gestartet.)

![farbe](https://user-images.githubusercontent.com/37038767/49172145-8636e080-f340-11e8-9c85-f9bf49a56551.gif)

**Comment by thkl** [comment]
siehe #66 eine Änderung von Werten auf einer Lampe führt im HUE Gateway nicht zu einer Änderung des Gruppendevices ...
Das macht ja auch Sinn denn dann müssten ja rückwirkend auch alle anderen Lampen in der Gruppe geändert werden.

Gruppen sind her so als WriteOnly zu betrachten
