### ISSUE TITLE
Update scheitert

### ISSUE THREAD

**Issue by AndynordSee** [thkl/Homematic-Virtual-Interface#69]
Kann kein update durchführen .

Das Update wird mir angeboten, "0.2.66 |ÊNew Version : 0.2.68 - Update".
Doch nach start des Updates kommt nach einigen Minuten kommt nur  
URL : " http://192.168.23.xx:8300/index/?doupdate" 
" Diese Seite funktioniert nicht 
192.168.23.xx hat keine Daten gesendet.
ERR_EMPTY_RESPONSE "

System 3.41.11.20181126 
HVL : 0.0.7

#59

**Comment by Kraehe1806** [comment]
https://github.com/thkl/Homematic-Virtual-Interface/issues/9

**Comment by Kraehe1806** [comment]
guck mal unter dem Link oben nach
