### ISSUE TITLE
Fehler beim installieren auf Raspberry- Was mache ich falsch?

### ISSUE THREAD

**Issue by Emmy77** [thkl/Homematic-Virtual-Interface#70]
Fehler beim installieren auf Raspberry- Was mache ich falsch?

![bildschirmfoto 2018-12-13 um 18 23 25](https://user-images.githubusercontent.com/45855768/49956392-59b8c200-ff05-11e8-8c78-54d96a5cbb3f.png)

**Comment by MathiasH82** [comment]
Ich bekomme es auch nicht installiert wenn ich die tar.gz Datei versuche im Raspberrymatic Einstellungen > Systemsteuerung > Zusatzsoftware zu installieren. 
Bekomme dann nen Error (104)

**Comment by henrydiesner** [comment]
Bekomme leider den gleichen Fehler. Liegts am HVI oder an RaspberryMatic?

**Comment by bvol** [comment]
Mit dem Pi user wirst Du keinen Erfolg haben. Wenn dann mit sudo..... Pi hat keine Root Rechte.

**Comment by thkl** [comment]
closed as https://github.com/thkl/Homematic-Virtual-Interface/blob/master/raspberrymatic_installer/hvl-raspb-0.0.10.tar.gz is working on RM
