### ISSUE TITLE
Geräte bleiben nach Löschen im Posteingang

### ISSUE THREAD

**Issue by matzempc** [thkl/Homematic-Virtual-Interface#72]
Geräte die entfernt wurden erscheinen im Posteingang! Dies habe ich erst entdeckt nachdem ich HVL (versucht habe) komplett zu entfernen, hier lassen Sie sich nicht mehr löschen da bei Interface/Kategorie "null" steht.
Gibt es eine Möglichkeit die Geräte wieder los zu werden?

**Comment by thkl** [comment]
Siehe auch readme hier.
