### ISSUE TITLE
Plugin für Selve Commeo Rolladenantriebe erstellen

### ISSUE THREAD

**Issue by armin34320** [thkl/Homematic-Virtual-Interface#80]
Das Homematic-Virtual-Interface Famework scheint mir optimal für eine Emulation der Selve Commeo Rolladenantriebe als HM-LC-Bl1-FM Geräte.

Die Rolladen selber können über den Selve RF Gateway USB Stick (hab ich) über ein xml Protokoll auf der seriellen Schnittstelle angesteuert und ausgelesen werden.

Ich würde gerne das Plugin mit entsprechender Hilfe der Contributors erstellen wollen.

Dafür benötige ich einige genauere Details über die Verwendung des Farmeworks. 
Genauer: 

 - Gerätedatei für den HM-LC-Bl1-FM erstellen
 - wie werden die Geräte verwaltet
 - wie werden die Geräte in der CCU angelernt (neu oder Test auf schon vorhanden)
 - wie werden Kommandos von der CCU empfangen (events/callbacks)
 - wie werden die Werte an die CCU geschickt

Vielen Dank.

**Comment by comtel2000** [comment]
@armin34320: die HM Geräte werden als json hinterlegt und die Kommunikation relativ selbsterklärend in einer ..Platform.js. Hier ein einfaches Bsp. für ein externes Plugin:
https://github.com/comtel2000/homematic-virtual-darkskyweather

Sonst schau dir die anderen plugins hier im Projekt an.

**Comment by thkl** [comment]
Es gibt das Dummy Plugin dort ist beschrieben wie das Ganze funktioniert. Und auch wie Gerätetypen dem Framework hinzugefügt werden können.

**Comment by armin34320** [comment]
Danke für die prompte Antwort.
Werde mich da mal durcharbeiten.
