### ISSUE TITLE
WebGUI lässt sich nicht aufrufen (pivccu3)

### ISSUE THREAD

**Issue by manoloxxl** [thkl/Homematic-Virtual-Interface#81]
Hi,

durch Zufall bin ich auf das Plugin gestoßen und musste es direkt auf meinem Pi installieren. Es handelt sich um ein pivccu image (CCU3 läuft in einem Container mit eigener IP) auf dem noch eine homebridge läuft (WebGUI: <IP-RASPI>/8081). 

In der Anleitung (https://appproject.de/Hausautomatisierung/HVL/HVL_Layer_Homematic.html) zum HVL steht, ich kann bzw. muss die HVL WebGUI über <IP-RASPI>/8182 aufrufen. 

Leider bekomme ich nach der Installation weder die Gui zum HVL noch meiner homebridge angezeigt (ging vorher).

Habe ich etwas falsch gemacht? Muss ich überhaupt auf die GUI?

Grüße
Manuel

**Comment by manoloxxl** [comment]
Kann geschlossen werden. Folgt man der Anleitung im Homematic-Forum gehts!

**Comment by LevelOne2k** [comment]
Und welche Anleitung ist das?

**Comment by ConBeeUser** [comment]
Ein Link zur Anleitung wäre tatsächlich toll gewesen.
