### ISSUE TITLE
Installation Package for official ccu3

### ISSUE THREAD

**Issue by mpietruschka** [thkl/Homematic-Virtual-Interface#85]
Hej! Is there an existing installation package for the official ccu3? Or at least a little installation instruction?

**Comment by mpietruschka** [comment]
I could imaginge HVL as fully selfcontained addon. With the needed NodeJS and anything else.

**Comment by thkl** [comment]
https://github.com/thkl/Homematic-Virtual-Interface/blob/master/raspberrymatic_installer/hvl-raspb-0.0.10.tar.gz was tested on a Respberrymatic and should also work on a CCU3.

The addon will install all parts of the core system on CCU restart. You will need a second reboot after that to make sure the CCU knows about the new hardware layer ....

**Comment by mpietruschka** [comment]
thanks!
