### ISSUE TITLE
Unterstützung für neue x86-basierte RaspberryMatic Version

### ISSUE THREAD

**Issue by jens-maus** [thkl/Homematic-Virtual-Interface#86]
Mit der nächsten kommenden RaspberryMatic version wird es eine neue zusätzlich Plattform für RaspberryMatic geben. Dabei handelt es sich um eine x86 (i686) basierte Version die als erste Iteration für das erzeugen einer virtuellen RaspberryMatic unter Virtualisierungsumgebungen (sog. "ova" platform) herausgebracht wird.

Da die Binaries im hm-tools Addon momentan lediglich ARM-basierte Binaries sind funktioniert dieses Addon momentan leider nicht mit der neuen "ova" Plattform. Es wäre daher schön wenn das Addon entsprechend um diese zusätzlich Plattform erweitert werden könnte und binaries mit ausgeliefert werden die auf einem i686/x86 System lauffähig sind.

Mehr Information zur neuen "ova" Plattform findet man momentan hier:
https://homematic-forum.de/forum/viewtopic.php?f=65&t=54055#p538104

**Comment by thkl** [comment]
closing as https://github.com/thkl/Homematic-Virtual-Interface/blob/master/raspberrymatic_installer/hvl-raspb-0.0.10.tar.gz was tested on a VBox RM
