### ISSUE TITLE
HVL und RaspberryMatic funktioniert nicht

### ISSUE THREAD

**Issue by LevelOne2k** [thkl/Homematic-Virtual-Interface#89]
Hallo @thkl ,

ist HVL problemlos auf der RaspberryMatic nutzbar?

**Comment by LevelOne2k** [comment]
@thkl ,

leider nicht. Ich habe das Addon gerade mal installiert.

 Wenn man hier auf den Link klickt, ist dieser in der Adresszeile erstmal falsch:
<img width="800" alt="Bildschirmfoto 2020-01-12 um 16 31 56" src="https://user-images.githubusercontent.com/25386824/72221252-2b1e7800-3559-11ea-9af0-8369c2be99a6.png">
Das ist der Link der sich dann öffnet: http://192.168.178.56/'/addons/hvl/'

Wenn ich ihn dann abändere: http://192.168.178.56/addons/hvl/ 

Dann bleibt die Seite einfach nur weiß.

Bei mir läuft RaspberryMatic 3.47.22.20191026

@jens-maus Muss seit einer gewissen Version X von RaspberryMatic auf etwas geachtet werden? Das HVL Addon für die RaspberryMatic wurde ja schon länger nicht mehr upgedatet. Hast Du eine Idee?

Danke euch beiden!

**Comment by thkl** [comment]
Ich vermute mal es muss eine andere Version von node.js auf der RM-X installiert werden.
Da ich aber sowas nicht betreibe, kann ich da nicht viel sagen.

**Comment by LevelOne2k** [comment]
Hm, wie könnten wir HVL auf dem RM wieder zum laufen bringen? Kann ich irgendwie helfen?

**Comment by thkl** [comment]
Es wird per default in der postinstall.sh  die ARM Node Version installiert.
Wenn die RM X ein x86 basierendes System ist müsste diese Version installiert werden: 

https://nodejs.org/dist/v13.6.0/node-v13.6.0-linux-x64.tar.xz

allerdings müsste das im Installer Script gemacht werden, damit hinterher der Rest gemacht werden kann.

**Comment by LevelOne2k** [comment]
Also da ich die RM auf einem Pi installiert habe, wird es wohl auch ARM sein.

**Comment by thkl** [comment]
hmm ich müsste mal die Zeit finden, das zu testen. Ich lasse HVL auf einem eigenen PI laufen.

**Comment by LevelOne2k** [comment]
Das wäre echt klasse von Dir!

**Comment by jens-maus** [comment]
Oder du stellst es so um das HVl die bereits vorinstallierte nodejs 10 version nutzt.

**Comment by jens-maus** [comment]
Achja, und RaspberryMatic x86 braucht 32bit (i686) binaries. D.h. Die nodejs version für x64 wird nicht funktionieren.

**Comment by thkl** [comment]
Ok das würde gehen. Aber nur die x86 RM hat node vorinstalliert ? Die ARM Version nicht ?

**Comment by LevelOne2k** [comment]
Die RaspberryMatic x86 läuft doch nicht auf einem Raspi @jens-maus

**Comment by jens-maus** [comment]
Klar, jedes RaspberryMatic hat genauso wie die CCU3 bereits nodejs onboard.

**Comment by thkl** [comment]
breaking news ... ok ich passe dann mal den installer an

**Comment by jens-maus** [comment]
So breaking news ist das nun auch wieder nicht. Schon die erste CCU3 Firmware version hatte nodejs dabei.

**Comment by AdlerCentauri** [comment]
Wenn man HVL über die Zusatzsoftware deinstallieren will, dann klappt das nicht:
<img width="447" alt="Bildschirmfoto 2020-01-13 um 02 22 21" src="https://user-images.githubusercontent.com/37038767/72228987-a3158e00-35ab-11ea-9fe7-7f8bb91d0503.png">

**Comment by comtel2000** [comment]
@LevelOne2k 
Ich habe HVL auf einen Raspberrymatic mit aktueller Version ohne Probleme am laufen.
Allerdings ist die spezielle Raspberrymatic Plugin Version 0.0.7.
Deine Version 0.0.9 ist vermutlich nicht für die CCU3 geeignet?

**Comment by TheRealTremes** [comment]
@thkl hast du die Anpassung schon vorgenommen?

**Comment by thkl** [comment]
Ich brauch erst mal einen freien PI für eine  RM Testinstallation

**Comment by jens-maus** [comment]
@thkl Hast du vielleicht ein Synology/QNAP Nas oder vmWare ESXi, Proxmox oder einfach VirtualBox auf dem Laptop dann kannst du doch seit einigen Versionen ein virtuelles RaspberryMatic betrieben (siehe https://github.com/jens-maus/RaspberryMatic/wiki/Installation#grundinstallation-virtuell)

**Comment by thkl** [comment]
ja doch ;o) ....

**Comment by TheRealTremes** [comment]
Wenn er RM doch virtuell betreibt, ist es doch x86 und wenn er das HVL darauf anpasst, dann würde es doch immer noch nicht für ARM, sprich einem Pi gehen?

**Comment by thkl** [comment]
*DAS* ist ja die Anpassung des Installers. Die alte, (feste) Installation der ARM Node Version raus und dafür die schon in RM vorhandene nutzen.

**Comment by TheRealTremes** [comment]
Ah alles klar, dann kannst du RM natürlich auch in einer virtuellen Umgebung laufen lassen.

**Comment by AdlerCentauri** [comment]
Habe RaspberryMatic gerade mal mit VirtualBox in Betrieb genommen. Klappt wunderbar nach dieser Anleitung https://github.com/jens-maus/RaspberryMatic/wiki/Installation-VirtualBox

**Comment by thkl** [comment]
müsste mit https://github.com/thkl/Homematic-Virtual-Interface/commit/49afc794e18e1a508f39f5673b69ba82edd19e4b gehen ... 

Nicht getestet, da gerade keine RM zur Hand ...

**Comment by TheRealTremes** [comment]
@thkl danke erstmal. Aber warum installierst du dir die RM nicht in dir VirtualBox? Das dauert keine 5 Minuten und die RM isr online.

**Comment by LevelOne2k** [comment]
Hallo @thkl 

HVL scheint nun wieder auf der RM zu funktionieren. Danke dafür!

Ein paar Fragen und Dinge:

Nutzt HVL jetzt das [onboard nodejs](https://github.com/thkl/Homematic-Virtual-Interface/issues/89#issuecomment-573449851) welches bei der CC3 FW und RM dabei ist?

Als ich bei der Zusatzsoftware
<img width="809" alt="Bildschirmfoto 2020-01-18 um 04 17 12" src="https://user-images.githubusercontent.com/25386824/72657817-709fd280-39a9-11ea-9e0f-aaf7d32ce880.png">
auf Einstellen geklickt habe, konnte die Seite erst nicht geöffnet werden. Dann habe ich in der Adresszeile eingegeben ```http://ip_vom_rm/addons/hvl``` dann erschien das WebIF von HVL. Wenn ich jetzt in der Zusatzsoftware auf Einstellen klicke, dann wird HVL sofort mit ```http://ip_vom_rm:8300/``` geöffnet. Ist es ein Bug das es beim ersten klicken auf Einstellen nicht direkt geöffnet werden konnte?

In der Systemsteuerung gibt es keinen "Virtual Layer" Button mehr:
<img width="1440" alt="Bildschirmfoto 2020-01-18 um 04 21 01" src="https://user-images.githubusercontent.com/25386824/72657849-ffacea80-39a9-11ea-803d-18fd6a8675f2.png">

Das WebIF von HVL ist auf englisch:
<img width="1171" alt="Bildschirmfoto 2020-01-18 um 04 21 54" src="https://user-images.githubusercontent.com/25386824/72657854-1f441300-39aa-11ea-9584-528278e21f28.png">

Das deinstallieren von HVL funktioniert nicht bzw. es gibt eine Fehlermeldung:
<img width="816" alt="Bildschirmfoto 2020-01-18 um 04 23 23" src="https://user-images.githubusercontent.com/25386824/72657881-5ca8a080-39aa-11ea-8566-27bdcba956c8.png">

Danke! Wird mal wieder Zeit für eine Spende. Stimmt deine PayPal URL hier noch?

**Comment by thkl** [comment]
Ok super das es funktioniert. 
Die Sprache hängt am Browser. Ggf geht da was verloren. 

Der Button fehlt weil das Tool, was das File für die Buttons ändert nur arm ist.  Das baue ich mal noch um. 

Uninstall sollte funktionieren trotz Meldung.

**Comment by thkl** [comment]
Das erste Problem (nicht erreichbar) könnte am Timing liegen. Nach der Installation des Plugins und eines reboots werden erst die eigentlichen Teile von hvl geladen und nach einem erneuten Reboot dann HVL gestartet. Das liegt daran, das die Install Routine erst nach dem 1. Reboot das Interface File schreibt.

**Comment by thkl** [comment]
so das RaspAddon ist in Version 0.0.10 verfügbar ... es sollte jetzt alles funktionieren.

**Comment by LevelOne2k** [comment]
@thkl bekomme die Meldung wenn ich installieren will
<img width="418" alt="Bildschirmfoto 2020-01-18 um 19 24 20" src="https://user-images.githubusercontent.com/25386824/72668524-2f9ad300-3a28-11ea-8f5e-3273992b548b.png">

**Comment by thkl** [comment]
Also ich hab mir jetzt eine virtuelle RM geklöppelt .. https://github.com/thkl/Homematic-Virtual-Interface/raw/master/raspberrymatic_installer/hvl-raspb-0.0.10.tar.gz lässt sich als Addon installieren und die HVL Installation inkl Button in der Systemsteuerung läuft durch

**Comment by LevelOne2k** [comment]
Bei mir gehts nicht. Bekomme immer die Fehlermeldung we oben gepostet.

**Comment by LevelOne2k** [comment]
Habe RM in der Virtuellen gerade nochmal neu aufgesetzt, nun geht es.

Muss die RM nach der Installation neugestartet werden?

**Comment by thkl** [comment]
Die RM muss nach der Installation einmal neu gestartet werden. Die Installation erzeugt erst den zusätzlichen Hardwarelayer in der CCU und nur bei einem Neustart weiß dann Rega von dem Ding ...

**Comment by LevelOne2k** [comment]
Ich muss die RM 2x neu starten. Das erste Mal ist damit HVL dann überhaupt erreichbar ist, und das zweite Mal ist damit HVL über die Schnittstelle verbunden ist. Ansonsten erscheint in HVL diese Meldung:

> 0 aktive Verbindungen (Letze Meldung )
Es scheint, das die CCU nichts vom Homematic-Virtual-Layer weiss. Wenn Du sicher bist, das die IP richtig ist und die Einstellungen in der InterfacesList.xml der CCU stimmen, dann kann ein CCU Neustart für Abhilfe sorgen.

Nach dem 2. Neustart ist dann alles in Ordnung:

> 2 aktive Verbindungen (127.0.0.1:9292/bidcos | 127.0.0.1:1999/ | Letze Meldung Sun Jan 19 2020 18:17:46 GMT+0100 (CET))

Ist das auch normal, dass mal 2x einen Neustart machen muss?

**Comment by thkl** [comment]
Das ist genau das, was ich oben beschrieben habe.
Und ja das ist normal. Die CCU installiert das Addon zwar schon, aber erst beim Neustart wird geschaut, ob das core System installiert werden muss.

**Comment by To-Fu112** [comment]
Hallo, ich habe seit heute ein Problem mit HVL. Ich hatte es erst vor einer Woche installiert, um es mal zu testen, da ich so viele gute Sachen gelesen habe. Hatte bislang eine meiner Hue Lampen damit eingebunden. Nun habe ich gestern auf meine modifizierte CCU3 mit Raspberrymatic auf die Version: 3.53.30.20200919 aktualisiert. Seit dem ist HVL nicht mehr erreichbar. Auch meine Huelampe funktioniert nicht mehr. Hat da sonst noch jemand das Problem, oder eine Idee woran es liegen könnte?
Vielen Dank im voraus!

**Comment by captaincanada** [comment]
Hallo liebe Community,
Danke erstmal an thkl für die mega arbeit!
würde gerne spenden wenn beibmir aich alles läuft... :)
folgendes Problem gibt es zu lösen....

hvl wurde über den quickinstall Code auf einem Pi neben iobroker installiert. 

danach ging der Zugriff im Browser über den Port :8182

in den Einstellungen im hvl habe ich unwissend den Haken bei der passwortvergabe gesetzt...
dort wo Admin passwort User: admin steht.
dachte da muss was von der CCU3 rein, da ich ein anderes Passwort verwende.

das Ende vom lieb ist, dass ich jetzt nimma über den Browser darauf zugreifen kann und nicht weiß wie ich das wieder weg bekomme, geschweige denn den hvl auf dem Pi neu installiere...

wenn ich es versuche zu überspielen ändert sich nicht viel :(

um Hilfe wäre ich sehr dankbar und evtl einen kleinen Schubs für "nichtprogrammierer" wie ich die ip zum Schluss auf aktiv bekomme. den Wiki install Eintrag hab ich befolgt... hat aber alles nicht geklappt. node und npm sind erst die tage aktualisiert worden. 

vielen dank an alle die helfen können 👍
