### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by rbartholomay** [thkl/Homematic-Virtual-Interface#9]
Hi,

I get the following screen:

![bildschirmfoto 2017-10-06 um 08 16 09](https://user-images.githubusercontent.com/1138142/31265374-ce75ad48-aa6e-11e7-9641-d7248b79e299.png)

But when I click on update and restart, the update will not installed and appear again. What's wrong?

**Comment by thkl** [comment]
yep the updater is broken until version 0.2.56 ;o( you have connect via ssh to your pi.
then cd to /home/pi and run the update command : npm i homematic-virtual-interface

**Comment by rbartholomay** [comment]
Hmm...  i use the RaspberryMatic addon - there is no home/pi?

**Comment by thkl** [comment]
oh sorry on raspberrmatic its in /usr/local/addons/hvl/ and there are no links from node or npm to /bin so the update command is:

```
cd /usr/local/addons/hvl/
/usr/local/addons/hvl/node/bin/node /usr/local/addons/hvl/node/bin/npm i homematic-virtual-interface
```

**Comment by rbartholomay** [comment]
Perfect!!!  Thanks!
