### ISSUE TITLE
HVL formatiert Eintrag in der InterfacesList.xml falsch & falschen Port (8182 statt 7000)

### ISSUE THREAD

**Issue by LevelOne2k** [thkl/Homematic-Virtual-Interface#93]
Hallo!

Ich habe gerade bei einem Kollegen auf einem Pi HVL installiert.

Als ich im WebIF von HVL unter CCU Info die Verbindung hinzugefügt habe und den Eintrag angeklickt habe damit der Eintrag in der InterfacesList.xml für HVL vorgenommen wird, bootete die CCU nicht mehr bzw. es hat 10 Minuten gedauert bis die CCU oben war. Der Screen blieb die ganze Zeit hier stehen:
<img width="632" alt="Bildschirmfoto 2020-01-19 um 22 47 04" src="https://user-images.githubusercontent.com/25386824/72689117-4f0c2b80-3b0e-11ea-9d77-69aa8f730982.png">

Ich habe dann alles nochmal von neu gemacht. Aber auch hier wieder, nachdem von HVL der Eintrag in der InterfacesList.xml vorgenommen wurde, ging es erst nach 10 Minuten weiter. HVL hatte auch keine Verbindung zur CCU bzw. In HVL stand bei der CCU Info etwas ähnliches wie "Es scheint als würde die CCU HVL noch nicht kennen ..."

Dann sah ich mir die InterfacesList.xml an, und folgender Eintrag war vorhanden:
````<ipc><name>HVL</name><url>xmlrpc://192.168.178.32:8182</url><info>HVL</info></ipc></interfaces>````

Dabei kam mir der Port 8182 etwas komisch vor. Als ich ihn dann auf 7000 abgeändert habe, ging es immer noch nicht. Die CCU bzw. RM brauchte ewig bis sie erreichbar war, und die CCU wusste immer noch nichts von HVL.

Dann habe ich den HVL Eintrag in der InterfacesList.xm wie folgt geändert:
(bekomme die Formatierung hier nicht hin, deshalb als Bild)
<img width="409" alt="Bildschirmfoto 2020-01-19 um 22 58 06" src="https://user-images.githubusercontent.com/25386824/72689193-34868200-3b0f-11ea-9c66-7239bde1bbd5.png">

Die gesamte InterfacesList.xml sieht nun so aus:
<img width="380" alt="Bildschirmfoto 2020-01-19 um 22 59 01" src="https://user-images.githubusercontent.com/25386824/72689211-56800480-3b0f-11ea-9cdc-3a1a03d0ba7d.png">

Dann habe ich die Formatierung in der InterfacesList.xml mal beibehalten und den Port von 7000 wieder auf 8182 geändert. Hier aber wieder dasselbe Spiel: Die CCU brauch ewig bis sie erreichbar ist, und die CCU weiß dann nichts von HVL. Dann wieder zurück auf Port 7000 und alles ist gut. Die CCU fährt normal hoch und die CCU weiß von HVL.

Ich denke das HVL den Eintrag in der InterfacesList.xml mit Port 8182 macht, ist falsch und korrekt wäre 7000. Seit es HVL gibt, nutze ich es selber und habe bei mir auch 7000 stehen. Aber bei der Installation bei einem Kollegen wurde wie gesagt 8182 eingetragen statt 7000. Daher war für mich klar, dass ich bei ihm die 8182 auf 7000 ändern muss.

Und es funktionierte wie gesagt erst, als der HVL Eintrag in der InterfacesList.xml korrekt formatiert war, obwohl der Port stimmte. So wie ich gelesen habe, meint @jens-maus auch, dass die Formatierung in der InterfacesList.xml schon korrekt sein sollte, und z.B. nicht so:
<img width="705" alt="Bildschirmfoto 2020-01-19 um 23 05 38" src="https://user-images.githubusercontent.com/25386824/72689297-4157a580-3b10-11ea-879f-1bd424e5625c.png">

Ich habe dann nur um sicher zu gehen, RM und HVL (jeweils auf getrennten Pi's) nochmal neu installiert. Aber auch hier, hat HVL den Eintrag in der InterfacesList.xml nicht korrekt formatiert und mit Port 8182 angelegt.

**Comment by thkl** [comment]
In der RM wird der Port 8183 verwendet.  Außerhalb der RM (also auf einem eignen Pi) Port 7000.

**Comment by LevelOne2k** [comment]
Ja, aber in diesem Fall wurde HVL außerhalb auf einem extra Pi installier. Nicht als CCU/RM Addon deshalb hätte HVL den Port 7000 in die InterfacesList.xml eintragen müssen. 

Ich denke, HVL hat hier nicht unterschieden ob es als Addon direkt auf der CCU installiert wurde, oder außerhalb.

**Comment by thkl** [comment]
Ich hab rausgefunden, woran es liegt und ändere das im Core schnellstmöglich...

**Comment by LevelOne2k** [comment]
Danke sehr!

**Comment by thkl** [comment]
Templatefehler im Insertion Command

**Comment by LevelOne2k** [comment]
Der Eintrag in der InterfacesList.xml wird nun von HVL mit den korrekten Ports erstellt.

Allerdings ist mir aufgefallen, dass die Formatierung noch nicht korrekt ist:
<img width="676" alt="Bildschirmfoto 2020-01-21 um 08 49 27" src="https://user-images.githubusercontent.com/25386824/72785287-2cbc0000-3c2b-11ea-8fca-8e34dbc00851.png">
Die CCU hat wieder um die 10 Minuten gebraucht bis die WebUI erreichbar war und die CCU wusste von HVL auch nichts.

Als ich die Formatierung dann angepasst habe:
<img width="427" alt="Bildschirmfoto 2020-01-21 um 08 56 18" src="https://user-images.githubusercontent.com/25386824/72785613-e7e49900-3c2b-11ea-8b9f-2c1d5e269e9c.png">
Ist die CCU sofort durchgestartet und die CCU wusste von HVL.

Habe das ganze jetzt 3x via kompletter Neuinstallation durch, das Ergebnis war immer dasselbe.
