### ISSUE TITLE
HVL Geräte "19er FB" lassen sich nicht bedienen und der CCU nicht konfigurieren

### ISSUE THREAD

**Issue by LevelOne2k** [thkl/Homematic-Virtual-Interface#94]
Hallo!

Ich habe HVL heute neu installiert und mit einer frischen RM verbunden. 
(HVL und RM laufen auf getrennten Pi's)

Ich habe u.a. die HVL Plugins Pioneer und Harmony installiert, aktiviert und konfiguriert. Beide 19er FB wurden zur CCU geschickt "HM-RC-19 HarmonyAct" und "HM-RC-19 PioneerAVR0"

Beide Geräte stehen in der CCU auf
CONFIG
LOWBAT
UNREACH
<img width="1407" alt="Bildschirmfoto 2020-01-19 um 23 19 43" src="https://user-images.githubusercontent.com/25386824/72689494-34d44c80-3b12-11ea-96b9-debe3cc73c51.png">

Wenn ich die 19er FB in der CCU einstellen will, dann gibt es einen Fehler:
<img width="1440" alt="Bildschirmfoto 2020-01-19 um 23 33 54" src="https://user-images.githubusercontent.com/25386824/72689678-3c94f080-3b14-11ea-965d-5191794ee32f.png">
<img width="1440" alt="Bildschirmfoto 2020-01-19 um 23 23 22" src="https://user-images.githubusercontent.com/25386824/72689555-c643be80-3b12-11ea-9788-09875fdff074.png">

In der CCU WebUI unter Status und Bedienung --> Geräte lassen sich die Geräte über beide 19er FB nicht bedienen. Z.B. auf der Harmony werden keine Aktivitäten gestartet.

Im HVL WebIF kann ich die Harmony bedienen. Aktivitäten und Harmony Actions funktionieren. Die Verbindung von HVL zu Harmony steht also.

Dann habe ich mal das Hue Plugin installiert und hier funktioniert alles. Die RGBW Controller werden zur CCU geschickt und die Hue Lampen lassen sich über die CCU über die RGBW Geräte bedienen. Auch kann ich die "HVL Hue RGBW" Geräte in der CCU Einstellen, es gibt keinen Fehler:
<img width="1438" alt="Bildschirmfoto 2020-01-19 um 23 26 19" src="https://user-images.githubusercontent.com/25386824/72689581-1e7ac080-3b13-11ea-9a83-803a1363a9c3.png">

Scheinbar machen derzeit nur die 19er FB Geräte bei einer Neuinstallation Probleme.

Seitdem es HVL gibt, nutze ich es auf meinem Produktiv System. Mit u.a. dem Harmony und Pioneer Plugin. Alles funktioniert, bei beiden Geräten gibt es auch keine Meldung wie
CONFIG
LOWBAT
UNREACH
<img width="1438" alt="Bildschirmfoto 2020-01-19 um 23 28 14" src="https://user-images.githubusercontent.com/25386824/72689605-63065c00-3b13-11ea-89d8-5e8420a191ac.png">
<img width="1440" alt="Bildschirmfoto 2020-01-19 um 23 28 41" src="https://user-images.githubusercontent.com/25386824/72689612-731e3b80-3b13-11ea-910d-bee80402e429.png">

Auch lassen sie sich ohne Fehlermeldung einstellen:
<img width="1440" alt="Bildschirmfoto 2020-01-19 um 23 29 19" src="https://user-images.githubusercontent.com/25386824/72689623-9648eb00-3b13-11ea-929f-dfc9fb8fdbe2.png">

**Comment by LevelOne2k** [comment]
@thkl hast du hierzu evtl. schon eine Ahnung?

**Comment by thkl** [comment]
Ein recht tief sitzender Bug im Core.... hat bei boolean Parametern die falsche Antwort gegeben.
Dadurch waren die Geräte immer auf config_pending ... Die Daten wurden zwar gespeichert aber der CCU wurde nicht gesagt das die Config richtig übertragen wurde.
