### ISSUE TITLE
Vorgehensweise der Installation so noch korrekt?

### ISSUE THREAD

**Issue by LevelOne2k** [thkl/Homematic-Virtual-Interface#95]
Hallo!

Ist die Vorgehensweise der Installation so noch korrekt?

**Installation**
Es wird davon ausgegangen das node schon auf dem RaspberyPI installiert ist. Wenn nicht:
```
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install nodejs
```

Die Installation des Core Modules auf dem PI kann ( unter der Vorraussetzung node ist schon installiert) mit
```
cd /home/pi
npm install homematic-virtual-interface
```

Starten lässt sich der HVL auf dem Pi mit
```
/home/pi/node_modules/homematic-virtual-interface/bin/hmviservice start
```
Hier die Frage: Wie lässt man HVL automatisch starten z.B. nach einem Neustart des Pi.

**Comment by thkl** [comment]
1. Wie auch immer node.js installieren (hängt vom target system ab)
2. npm install homematic-virtual-interface
3. node ./node_modules/homematic-virtual-interface/lib/index.js

**Comment by LevelOne2k** [comment]
@thkl ich habe meinen Beitrag editiert.

**Comment by thkl** [comment]
ich auch
