### ISSUE TITLE
Alle Verbindungen entfernen funktioniert nicht

### ISSUE THREAD

**Issue by LevelOne2k** [thkl/Homematic-Virtual-Interface#97]
Hallo!

Wenn man hier drauf klickt:
<img width="233" alt="Bildschirmfoto 2020-01-21 um 01 29 27" src="https://user-images.githubusercontent.com/25386824/72765604-869dd500-3bed-11ea-9923-9f171fb0e4f8.png">
Und dann auf OK klickt:
<img width="449" alt="Bildschirmfoto 2020-01-21 um 01 30 15" src="https://user-images.githubusercontent.com/25386824/72765627-9ae1d200-3bed-11ea-867f-0fb3736a8b54.png">
Dann kommt nach dem klicken auf OK diese Seite:
<img width="1160" alt="Bildschirmfoto 2020-01-21 um 01 30 49" src="https://user-images.githubusercontent.com/25386824/72765640-ac2ade80-3bed-11ea-8a00-5c75c639f9e2.png">

Wenn man dann oben links auf Home klickt, dann sieht es wieder so aus:
<img width="1158" alt="Bildschirmfoto 2020-01-21 um 01 31 33" src="https://user-images.githubusercontent.com/25386824/72765658-c795e980-3bed-11ea-83bf-cf4837dd21c2.png">
Die Verbindung zur CCU ist nicht entfernt worden.

**Comment by thkl** [comment]
Macht exakt was es soll. Der Verbindungstoken zwischen CCU und HVL wird weggeworfen. 
Es entfernt nicht die Schnittstelle in der CCU.

**Comment by LevelOne2k** [comment]
@thkl Ach so, ich dachte da wird alles auf null gesetzt inkl. Löschung des HVL Eintrags in der InterfacesList.xml. Wäre das denn nicht auch besser wenn alles auf null gesetzt wird?

Und warum sieht man nach dem drücken auf der OK die $ Zeichen ect. Und das eine neue Version Verfügbar ist obwohl HVL aktuell ist? (3. Bild)
