### ISSUE TITLE
Harmony Actions werden nicht geladen

### ISSUE THREAD

**Issue by LevelOne2k** [thkl/Homematic-Virtual-Interface#99]
Hallo!

Auf einer neuen HVL Installation mit nur installiertem Harmony Plugin werden die Harmony Actions nicht geladen:
<img width="1159" alt="Bildschirmfoto 2020-01-21 um 09 43 17" src="https://user-images.githubusercontent.com/25386824/72788603-78be7300-3c32-11ea-8fe8-3281748752e4.png">

Die Harmony Activities sind da und funktionieren auch. Sowohl aus dem HVL WebIF als auch über die 19er FB

Ist im Log vielleicht was zu erkennen?:

> Tue Jan 21 2020 09:40:05 GMT+0100 (GMT+01:00)[homematic-virtual-harmonydevice - Harmony] [INFO] - next free found
Tue Jan 21 2020 09:40:05 GMT+0100 (GMT+01:00)[homematic-virtual-harmonydevice - Harmony] [INFO] - next free found
Tue Jan 21 2020 09:40:05 GMT+0100 (GMT+01:00)[homematic-virtual-harmonydevice - Harmony] [INFO] - next free found
Tue Jan 21 2020 09:40:05 GMT+0100 (GMT+01:00)[homematic-virtual-harmonydevice - Harmony] [INFO] - next free found
Tue Jan 21 2020 09:40:05 GMT+0100 (GMT+01:00)[homematic-virtual-harmonydevice - Harmony] [INFO] - next free found
Tue Jan 21 2020 09:40:03 GMT+0100 (GMT+01:00)[homematic-virtual-harmonydevice - Harmony] [INFO] - fetching activities
Tue Jan 21 2020 09:40:03 GMT+0100 (GMT+01:00)[Homematic Virtual Interface.Server] [ERROR] - Unhandled Rejection at: Promise {"exception":{}} reason: TypeError: Cannot read property 'getAvailableCommands' of undefined
    at /home/hvl/node_modules/homematic-virtual-harmonydevice/HarmonyClient.js:95:25
    at _fulfilled (/home/hvl/node_modules/homematic-virtual-harmonydevice/node_modules/q/q.js:854:54)
    at /home/hvl/node_modules/homematic-virtual-harmonydevice/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/home/hvl/node_modules/homematic-virtual-harmonydevice/node_modules/q/q.js:816:13)
    at /home/hvl/node_modules/homematic-virtual-harmonydevice/node_modules/q/q.js:624:44
    at runSingle (/home/hvl/node_modules/homematic-virtual-harmonydevice/node_modules/q/q.js:137:13)
    at flush (/home/hvl/node_modules/homematic-virtual-harmonydevice/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
Tue Jan 21 2020 09:40:03 GMT+0100 (GMT+01:00)[homematic-virtual-harmonydevice - Harmony] [INFO] - HarmonyHueServer Server is listening on: Port 7001
Tue Jan 21 2020 09:40:03 GMT+0100 (GMT+01:00)[homematic-virtual-harmonydevice - Harmony] [INFO] - Start talking to your harmony
Tue Jan 21 2020 09:40:03 GMT+0100 (GMT+01:00)[HomematicLogicalLayer] [INFO] - Skip HMServer
Tue Jan 21 2020 09:40:03 GMT+0100 (GMT+01:00)[Homematic Virtual Interface.Server] [INFO] - Add UPnP Service urn:schemas-upnp-org:device:basic:1
Tue Jan 21 2020 09:40:03 GMT+0100 (GMT+01:00)[homematic-virtual-harmonydevice - Harmony] [INFO] - No Hue Pluginname provided in hue_plugin_name. Skipping real Bridge mapping.
Tue Jan 21 2020 09:40:03 GMT+0100 (GMT+01:00)[Homematic Virtual Interface.Server] [INFO] - remove urn:schemas-upnp-org:device:basic:1 from UPnP
Tue Jan 21 2020 09:39:56 GMT+0100 (GMT+01:00)[HomematicLogicalLayer] [ERROR] - RPC Command Error HmIP-RF on if Error: Unknown XML-RPC tag 'TITLE' for init with http://192.168.191.65:7002,hvl_HmIP-RF
Tue Jan 21 2020 09:39:56 GMT+0100 (GMT+01:00)[HomematicLogicalLayer] [INFO] - CCU Response for ...Value () Error : (Error: Unknown XML-RPC tag 'TITLE')
Tue Jan 21 2020 09:39:56 GMT+0100 (GMT+01:00)[HomematicLogicalLayer] [INFO] - CCU Response for ...Value () Error : (Error: Unknown XML-RPC tag 'TITLE')
Tue Jan 21 2020 09:39:56 GMT+0100 (GMT+01:00)[HomematicLogicalLayer] [ERROR] - RPC Command Error BidCos-RF on if Error: Unknown XML-RPC tag 'TITLE' for init with http://192.168.191.65:7002,hvl_BidCos-RF
Tue Jan 21 2020 09:39:55 GMT+0100 (GMT+01:00)[homematic-virtual-harmonydevice - Harmony] [INFO] - HarmonyHueServer Server is listening on: Port 7001
Tue Jan 21 2020 09:39:55 GMT+0100 (GMT+01:00)[Homematic Virtual Interface.Server] [INFO] - Trying to load Localization from /home/hvl/node_modules/homematic-virtual-harmonydevice/Localizable.strings
Tue Jan 21 2020 09:39:55 GMT+0100 (GMT+01:00)[Homematic Virtual Interface.Server] [INFO] - Harmony initialized. Document Path is /home/hvl/node_modules/homematic-virtual-harmonydevice Plugin Instance: 0
Tue Jan 21 2020 09:39:55 GMT+0100 (GMT+01:00)[homematic-virtual-harmonydevice - Harmony] [INFO] - There is no hubIP .. skipping Harmony Client

Die IP 192.168.191.65 ist die von HVL. Der Harmony Hub hat die IP 192.168.191.16

**Comment by thkl** [comment]
ja steht ja da ... es können keine Actions von der Harmony gelesen werden. Warum und wieso ¯\_(ツ)_/¯

**Comment by LevelOne2k** [comment]
Komisch. Mit meinem Produktiv System und HVL Version 0.2.68 gibt es keine Probleme mit den Actions. Lassen sich auch bedienen.

Das Problem kam wohl erst mit der HVL Version 0.2.73. Habe HVL jetzt mehrmals neu installiert auf einem leeren Debian, kommt aber immer zum selben Ergebnis.

XMPP auf Harmony ist natürlich aktiviert.

**Comment by thkl** [comment]
Ich habe keine Harmony ich kann das leider nicht testen.
Aber an dem Harmony Plugin habe ich nichts geändert. Der Core hat auch nichts mit der Kommunikation zur Harmony zu tun.

**Comment by LevelOne2k** [comment]
LOOL hmmmpff ... Gerade das Harmony Plugin deakticiert und wieder aktiviert, nun sind die Drecks Actions da.
